create table if not exists `otc`.`GJ_G2010_ITEM_MARKET_INFO` (
	`ID` NUMERIC(19, 0) not null,
	`ITEM_CODE` VARCHAR(10) binary,
	`MARKET_NAME` VARCHAR(36) binary,
	`PRIORITY` NUMERIC(8, 0),
	`AUDIT_STATUS` CHAR(1) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPD_TIME` DATETIME,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`WEEKS` VARCHAR(240) binary,
	`TICKET_NUM` VARCHAR(60) binary,
	`NOLOGIN_IS_DISPLAY` VARCHAR(3) binary,
	`MALL_URL` VARCHAR(600) binary,
	`USER_RULE_ID` VARCHAR(600) binary,
	`PC_LINK` VARCHAR(600) binary,
	`BLACK_IMAGE_URL` VARCHAR(600) binary,
	`BLACK_IMAGE_ID` VARCHAR(120) binary,
	`BLACK_IMAGE_NAME` VARCHAR(120) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary,
	`YD_URL_NAME` VARCHAR(240) binary,
	`PC_URL_NAME` VARCHAR(240) binary,
	`JH_URL_NAME` VARCHAR(240) binary,
	`MARKETING_TAG` VARCHAR(15) binary,
	`XIAODIAN_LINK` VARCHAR(600) binary,
	`XIAODIAN_URL_NAME` VARCHAR(308) binary,
	`MARKET_IMG_URL` VARCHAR(600) binary,
	`MARKET_TYPE` CHAR(1) binary,
	`MARKET_START_TIME` DATETIME,
	`MARKET_END_TIME` DATETIME,
	`MARKET_IMG_NAME` VARCHAR(240) binary,
	`MARKET_IMG_ID` VARCHAR(240) binary,
	`PC_MARKET_URL` VARCHAR(600) binary,
	`PC_MARKET_ID` VARCHAR(120) binary,
	`PC_MARKET_NAME` VARCHAR(120) binary,
	`MARKET_REMARK` VARCHAR(600) binary,
	`OBJECT_TYPE` CHAR(1) binary,
	`IS_DISPLAY_OBJECT_NAME` CHAR(1) binary,
	`OBJECT_CODE` VARCHAR(60) binary,
	`BENCHMARK_TYPE` CHAR(1) binary,
	`IS_DISPLAY_BENCHMARK_NAME` CHAR(1) binary,
	`BENCHMARK_CODE` VARCHAR(60) binary,
	`PERIOD_TYPE` CHAR(1) binary,
	`MARKET_URL` VARCHAR(600) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_G2010_API_LOG_LS` (
	`SERIALNO` VARCHAR(60) binary,
	`CLIENTID` VARCHAR(60) binary,
	`BUSINACCOUNT` VARCHAR(60) binary,
	`FUNCTIONID` VARCHAR(60) binary,
	`BIZDATE` DATETIME,
	`KBN` CHAR(1) binary,
	`CIFACCOUNT` VARCHAR(60) binary,
	`SOURCE` CHAR(1) binary,
	`CALLTIME` NUMERIC(19, 0),
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`RESULT` LONGTEXT,
	`PARAMETER` LONGTEXT,
	`ID` NUMERIC(19, 0) not null,
	constraint `BIN$JRvB0lU90lrgYAB/AQBj0w==$0` primary key (`ID`)
);

create table if not exists `otc`.`YHZX_OFUND_PLAN` (
	`SERIAL_ID` VARCHAR(39) binary,
	`USER_CODE` NUMERIC(19, 0),
	`CIF_ACCOUNT` VARCHAR(39) binary,
	`CUST_CODE` VARCHAR(39) binary,
	`CUACCT_CODE` VARCHAR(39) binary,
	`MARKET` VARCHAR(39) binary,
	`TRADE_ACCOUNT` VARCHAR(39) binary,
	`BUSIN_TYPE` VARCHAR(39) binary,
	`BENCHMARK` VARCHAR(77) binary,
	`BENCH_DATA` VARCHAR(615) binary,
	`BALANCE` NUMERIC(19, 6),
	`PROD_TYPE` VARCHAR(15) binary,
	`PROD_CODE` VARCHAR(15) binary,
	`PROD_NAME` VARCHAR(308) binary,
	`BANK_NO` VARCHAR(15) binary,
	`BANK_ACCOUNT` VARCHAR(77) binary,
	`TERMINAL_SOURCE` VARCHAR(39) binary,
	`BUSIN_FLAG` VARCHAR(39) binary,
	`DEAL_FLAG` VARCHAR(3) binary,
	`DEAL_DATE` NUMERIC(8, 0),
	`DEAL_LOG` VARCHAR(308) binary,
	`DEBIT_WAY` VARCHAR(39) binary,
	`PLAN_CYCLE` NUMERIC(19, 0),
	`PLAN_UNIT` VARCHAR(39) binary,
	`PLAN_BEGIN_DATE` NUMERIC(8, 0),
	`PLAN_END_DATE` NUMERIC(8, 0),
	`UPDATE_TIME` NUMERIC(8, 0),
	`UPDATE_DATE` NUMERIC(8, 0),
	`ORDER_DATE` NUMERIC(8, 0),
	`TOKEN_SERIAL_NO` VARCHAR(308) binary,
	`USER_TOKEN` VARCHAR(615) binary,
	`OP_SITE` VARCHAR(154) binary,
	`BRANCH_NO` VARCHAR(12) binary,
	`OP_WAY` VARCHAR(3) binary,
	`PASSWORD` VARCHAR(39) binary,
	`REMARK` VARCHAR(154) binary
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_DAY_CNT` (
	`YMD` VARCHAR(10) binary not null,
	`PRO_TYPE` CHAR(1) binary not null,
	`CNT1` NUMERIC(19, 0),
	`CNT2` NUMERIC(19, 0),
	`CNT3` NUMERIC(19, 0),
	`CNT4` NUMERIC(19, 0),
	`CNT5` NUMERIC(19, 0),
	`CNT6` NUMERIC(19, 0),
	`SOURCE` CHAR(1) binary not null,
	`CNT11` NUMERIC(19, 0),
	`CNT22` NUMERIC(19, 0),
	`CNT33` NUMERIC(19, 0),
	`CNT44` NUMERIC(19, 0),
	`CNT55` NUMERIC(19, 0),
	`CNT66` NUMERIC(19, 0),
	constraint `BIN$JRvB0ljn0lrgYAB/AQBj0w==$0` primary key (`YMD`, `PRO_TYPE`, `SOURCE`)
)
comment='新客用户开户日期分布';

create table if not exists `otc`.`GJ_G2010_SHELF_SHOW_TYPE` (
	`SHELF_TYPE` VARCHAR(3) binary comment '货架类型("1.产品类货架
2.图片类货架
3.资讯类货架（默认1）")',
	`SHELF_BROWSE_WAY` VARCHAR(3) binary comment '货架阅读方式("1.横向阅读1列       2.横向阅读2列      3.横向阅读3列
4.纵向阅读1列（仅支持配1个产品）
5.纵向阅读2列
6.纵向阅读3列
7.纵向阅读动态不含轮播点1列（可配置多个产品）
8.纵向阅读动态含轮播点1列 9.纵向阅读1列特点标签增强
10.横向两列多行
11.纵向一列文字堆砌式
12.横向一列文字平铺式
13.主推方式展示
14.四列两行
17. 理财任务（仅支持图片类货架）")',
	`PROD_WITH_ENHANCED` VARCHAR(3) binary
);

create table if not exists `otc`.`GJ_G2010_SIMU_SERIAL_DATA` (
	`ID` NUMERIC(20, 0) not null comment '主键ID',
	`INIT_DATE` DATETIME not null comment '申请日期',
	`ORDER_NO` VARCHAR(60) binary comment '申请编号',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`BUSIN_ACCOUNT` VARCHAR(60) binary comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`PROD_CODE` VARCHAR(60) binary comment '产品代码',
	`ENTRUST_BALANCE` NUMERIC(19, 2) comment '申请金额',
	`COUNTER_SOURCE` VARCHAR(5) binary comment '产品中心产品编号("1":集中交易柜台 "2":OTC柜台)',
	`ORDER_STATUS` VARCHAR(5) binary,
	`CID_SOURCE` VARCHAR(12) binary comment '订单来源(默认：NEWMALL；PC端：PC)',
	`TRADE_TYPE` VARCHAR(12) binary,
	`OP_REMARK` VARCHAR(29) binary comment '操作备注',
	`TGLJ_INFO` VARCHAR(2400) binary comment '要素',
	`REGTEL` VARCHAR(16) binary comment '注册手机号',
	`ALLOT_NO` VARCHAR(240) binary comment '申请编号',
	`SUB_BUSIN_ACCOUNT` VARCHAR(120) binary comment '子账号，只有在投顾otc下单的会有值',
	`PRO_NAME` VARCHAR(240) binary comment '产品名称',
	`UP_REMARK` VARCHAR(60) binary comment '更新备注',
	`MATCHAMT` NUMERIC(65, 30) comment '（不知含义）',
	`MATCHQTY` NUMERIC(65, 30) comment '（不知含义）',
	`UPDATE_TIME` DATETIME comment '更新时间',
	constraint `BIN$JRvB0lZ70lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='私募流水数据';

create table if not exists `otc`.`GJ_G2050_PRO_ORDER` (
	`ID` NUMERIC(20, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`SECUM_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(20, 0),
	`PROD_NAME` VARCHAR(60) binary,
	`PROD_CODE` VARCHAR(60) binary,
	`ENTRUST_BALANCE` NUMERIC(20, 0),
	`ALLOT_NO` VARCHAR(60) binary,
	`ENTRUST_TIME` DATETIME(6),
	`CUST_NAME` VARCHAR(60) binary,
	`INIT_DATE` VARCHAR(24) binary,
	`SERIAL_NO` NUMERIC(20, 0),
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`ENTRUST_TYPE` VARCHAR(60) binary,
	`CLIENT_GENDER` VARCHAR(3) binary,
	`PROD_TA_NO` VARCHAR(12) binary,
	`SOURCE` VARCHAR(3) binary,
	`REMARK` VARCHAR(120) binary,
	`CID` VARCHAR(24) binary,
	`PROD_TYPE_CHILD` VARCHAR(12) binary,
	`UPDATE_TIME` DATETIME,
	`MATCHAMT` NUMERIC(22, 4),
	`UP_REMARK` VARCHAR(60) binary,
	`MATCHQTY` NUMERIC(22, 0),
	constraint `BIN$JRvB0lcD0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='预下单流水表';

create table if not exists `otc`.`GJ_BUY_ORDER` (
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`REC_UPD_TIME` DATETIME(6) comment '记录更新时间',
	`ID` NUMERIC(19, 0) not null comment '主键ID',
	`CUST_NUM` VARCHAR(60) binary not null comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary not null comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` NUMERIC(19, 0) comment '营业部代码',
	`BUY_TIME` DATETIME comment '购买时间',
	`TRANSFER_ORDER_NUM` VARCHAR(60) binary comment '转让订单编号',
	`PRO_NAME` VARCHAR(60) binary comment '产品名称',
	`PRO_CODE` VARCHAR(60) binary comment '产品代码',
	`PRO_NUM` VARCHAR(60) binary comment '产品编号',
	`BUY_QTY` NUMERIC(23, 4) comment '购买数量',
	`BUY_PRICE` NUMERIC(19, 4) comment '购买价格',
	`ORDER_STATUS` VARCHAR(3) binary comment '订单状态',
	`ORDER_NUM` VARCHAR(60) binary comment '订单编号',
	`SOURCE` VARCHAR(2) binary comment '来源',
	`CID` VARCHAR(120) binary comment '来源。PC表示“金融商城”',
	`TGLJ_INFO` VARCHAR(306) binary comment '推广链接',
	constraint `BIN$JRvB0lTZ0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='买家订单表';

create table if not exists `otc`.`GJ_OTC_REPORT_SIGN_CNT` (
	`CUST_NUM` VARCHAR(60) binary not null,
	`CNT1` NUMERIC(19, 0),
	`CNT2` NUMERIC(19, 0),
	`FIRST_SIGN_DATE` VARCHAR(10) binary
)
comment='客户签到统计表';

create table if not exists `otc`.`GJ_FNDCN_FUND_MNG` (
	`SEX` VARCHAR(5) binary,
	`POST` VARCHAR(192) binary,
	`DEGREE` VARCHAR(96) binary,
	`REASON` VARCHAR(240) binary,
	`REMARK` LONGTEXT,
	`RESUME` LONGTEXT,
	`ENDDATE` VARCHAR(33) binary,
	`JOBTITLE` VARCHAR(144) binary,
	`BIRTHDATE` VARCHAR(33) binary,
	`PATICTERM` NUMERIC(38, 18),
	`CHANGEDATE` VARCHAR(33) binary,
	`DATASOURCE` VARCHAR(120) binary,
	`ISPOSITION` NUMERIC(20, 8),
	`NOTICEDATE` VARCHAR(33) binary,
	`PERSONCODE` VARCHAR(20) binary,
	`PERSONNAME` VARCHAR(240) binary,
	`SECINNERCODE` VARCHAR(240) binary,
	`TRD_CODE` VARCHAR(15) binary,
	`IS_MASTERPIEC` VARCHAR(3) binary
);

create table if not exists `otc`.`GJ_G2020_FUNCTION_DETAIL` (
	`FUNCTION_ID` VARCHAR(14) binary comment '功能号',
	`FUNCTION_NAME` VARCHAR(60) binary comment '功能名称',
	`PARAMETER_CODE` VARCHAR(60) binary comment '参数英文',
	`PARAMETER_NAME` VARCHAR(2400) binary comment '参数中文',
	`PARAMETER_TYPE` VARCHAR(24) binary comment '字段类型',
	`IS_MUST` VARCHAR(9) binary comment '是否必须',
	`SAMPLE_VALUE` VARCHAR(240) binary comment '示例值',
	`REMARK` VARCHAR(2400) binary comment '备注',
	`TYPE` VARCHAR(5) binary comment '出入参类型',
	`SORT` NUMERIC(8, 0) comment '排序',
	`PARAMETER_CODE_OUT` VARCHAR(60) binary comment '出参'
)
comment='总线接口信息';

create table if not exists `otc`.`GJ_G9010_BUG_IMG_INFO` (
	`BUG_NUM` VARCHAR(120) binary not null,
	`IMG_ID` VARCHAR(240) binary,
	`IMG_NAME` VARCHAR(240) binary,
	`CREATE_TIME` DATETIME,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_G2020_FUNCTION_DAMPER_DATA` (
	`FUNCTION_ID` VARCHAR(10) binary,
	`DATA` LONGTEXT,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_CNT` (
	`YMD` VARCHAR(10) binary not null,
	`CNT1` NUMERIC(19, 0),
	`CNT2` NUMERIC(19, 0),
	`CNT3` NUMERIC(19, 0),
	`CNT4` NUMERIC(19, 0),
	`CNT5` NUMERIC(19, 0),
	`CNT6` NUMERIC(19, 0),
	`SOURCE` CHAR(1) binary not null,
	`CNT11` NUMERIC(19, 0),
	`CNT22` NUMERIC(19, 0),
	`CNT33` NUMERIC(19, 0),
	`CNT44` NUMERIC(19, 0),
	`CNT55` NUMERIC(19, 0),
	`CNT66` NUMERIC(19, 0),
	`CNTH2` NUMERIC(19, 0),
	`CNTH3` NUMERIC(19, 0),
	`CNTH22` NUMERIC(19, 0),
	`CNTH33` NUMERIC(19, 0),
	constraint `BIN$JRvB0ljX0lrgYAB/AQBj0w==$0` primary key (`YMD`, `SOURCE`)
)
comment='新客产品券种占比';

create table if not exists `otc`.`GJ_OTC_API_LOG_LS` (
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`LSH` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`FUNCTION_ID` VARCHAR(24) binary,
	`BIZ_DATE` DATETIME,
	`KBN` CHAR(1) binary,
	`RESULT` LONGTEXT,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`PARAMETER` LONGTEXT,
	`SOURCE` CHAR(1) binary,
	`CALL_TIME` NUMERIC(19, 0),
	constraint `BIN$JRvB0lhY0lrgYAB/AQBj0w==$0` primary key (`LSH`)
);

create table if not exists `otc`.`OFTIMERCONFIG` (
	`SERVERID` VARCHAR(60) binary not null,
	`ORDERDATE` VARCHAR(60) binary not null,
	`SNO` VARCHAR(60) binary not null,
	`SENDSN` VARCHAR(60) binary,
	`ORGID` NUMERIC(19, 0),
	`CUSTID` NUMERIC(19, 0),
	`FUNDID` NUMERIC(19, 0),
	`TACODE` NUMERIC(19, 0),
	`TAACC` VARCHAR(60) binary,
	`TRANSACC` VARCHAR(60) binary,
	`OFCODE` VARCHAR(60) binary,
	`TRDID` NUMERIC(19, 0),
	`ORDERAMT` NUMERIC(19, 2),
	`ORDERQTY` NUMERIC(19, 2),
	`REDEEMTYPE` VARCHAR(60) binary,
	`DEALDATE` VARCHAR(60) binary,
	`FAULTTIMES` NUMERIC(19, 0),
	`BEGINDATE` VARCHAR(60) binary,
	`ENDDATE` VARCHAR(60) binary,
	`DISCRATIO` NUMERIC(19, 8),
	`ACTIONMODE` VARCHAR(60) binary,
	`SENDDAY` NUMERIC(19, 0),
	`LASTACTIONDATE` VARCHAR(60) binary,
	`DEALFLAG` VARCHAR(6) binary,
	`DEALCODE` VARCHAR(6) binary,
	`SHARECLASS` VARCHAR(6) binary,
	`REMARK` VARCHAR(240) binary,
	`OPERWAY` VARCHAR(6) binary,
	`MONEYTYPE` VARCHAR(6) binary,
	`CANCELDATE` VARCHAR(60) binary,
	`ERRMSG` VARCHAR(600) binary,
	`RELATIVEDATE` VARCHAR(60) binary,
	`RELATIVESNO` VARCHAR(60) binary,
	`BANKID` VARCHAR(60) binary,
	`SOURCEFLAG` VARCHAR(6) binary,
	`STATUS` VARCHAR(6) binary,
	`TOTALCNT` NUMERIC(19, 0),
	`TOTALAMT` NUMERIC(19, 2),
	`TOTALQTY` NUMERIC(19, 2),
	`CUST_NUM` VARCHAR(17) binary,
	`OFNAME` VARCHAR(60) binary,
	`CUST_MANAGER` VARCHAR(120) binary,
	`CUST_MANAGER_MOBILE` VARCHAR(120) binary,
	constraint `BIN$JRvB0l+C0lrgYAB/AQBj0w==$0` primary key (`ORDERDATE`, `SNO`, `SERVERID`)
)
comment='定投明细表';

create table if not exists `otc`.`YHZX_ENTRUST` (
	`SERIAL_ID` VARCHAR(39) binary,
	`ENTRUST_ID` VARCHAR(39) binary,
	`BATCH_NO` VARCHAR(39) binary,
	`XH` NUMERIC(65, 30),
	`BUSIN_TYPE` VARCHAR(39) binary,
	`USER_CODE` NUMERIC(65, 30),
	`CUST_CODE` VARCHAR(39) binary,
	`MONEY_TYPE` VARCHAR(15) binary,
	`TERMINAL_SOURCE` VARCHAR(39) binary,
	`ENTRUST_AMOUNT` NUMERIC(19, 6),
	`ENTRUST_PRICE` NUMERIC(19, 6),
	`ENTRUST_BS` VARCHAR(12) binary,
	`ENTRUST_PROP` VARCHAR(12) binary,
	`PROD_CODE` VARCHAR(15) binary,
	`TA_CODE` VARCHAR(39) binary,
	`PROD_NAME` VARCHAR(308) binary,
	`REMARK` VARCHAR(1229) binary,
	`PROD_TYPE` VARCHAR(15) binary,
	`BUSIN_FLAG` VARCHAR(39) binary,
	`MARKET` VARCHAR(39) binary,
	`TRADE_ACCOUNT` VARCHAR(39) binary,
	`PAY_KIND` VARCHAR(39) binary,
	`PAY_ACCOUNT` VARCHAR(39) binary,
	`REBUY_AMOUNT` NUMERIC(19, 6),
	`REBUY_PERIODS` NUMERIC(19, 6),
	`CUACCT_CODE` VARCHAR(39) binary,
	`ENTRUST_DATE` NUMERIC(65, 30),
	`ENTRUST_TIME` NUMERIC(65, 30),
	`ENTRUST_SHARE` NUMERIC(19, 6),
	`ENTRUST_STATUS` VARCHAR(3) binary,
	`DEAL_FLAG` VARCHAR(3) binary,
	`DEAL_DATE` NUMERIC(65, 30),
	`DEAL_TIME` NUMERIC(65, 30),
	`CANCEL_DATE` NUMERIC(65, 30),
	`CANCEL_TIME` NUMERIC(65, 30),
	`OUT_SERIAL_NO` VARCHAR(39) binary,
	`OUT_SERIAL_NO2` VARCHAR(39) binary,
	`DEAL_LOG` VARCHAR(1229) binary,
	`SEND_MSG_FLAG` VARCHAR(3) binary,
	`GT_PASSFLAG` VARCHAR(3) binary,
	`GT_CTRLKINDS` VARCHAR(24) binary,
	`OUT_ENTRUST_ID` VARCHAR(39) binary,
	`GT_OUTBIZSNO` VARCHAR(39) binary,
	`GT_PROTOCLVER` VARCHAR(39) binary,
	`GT_PROTOCOLNO1` VARCHAR(39) binary,
	`GT_PROTOCOLNO2` VARCHAR(39) binary,
	`GT_DOUBLEVIDEO` VARCHAR(39) binary,
	`BANK_NO` VARCHAR(15) binary,
	`BIZ_SYS` NUMERIC(65, 30),
	`OP_CODE` VARCHAR(39) binary,
	`OP_BRANCH_NO` VARCHAR(39) binary,
	`OP_SITE` VARCHAR(308) binary,
	`OP_WAY` VARCHAR(39) binary,
	`OP_PROGRAM` VARCHAR(77) binary,
	`BRANCH_NO` VARCHAR(39) binary,
	`TERMINAL_INFO` VARCHAR(308) binary,
	`CIF_ACCOUNT` VARCHAR(39) binary,
	`DEVELOPER` VARCHAR(39) binary,
	`ELIG_CONFIRM_TYPE` VARCHAR(39) binary,
	`OUT_SERIAL_ID` VARCHAR(77) binary
);

create table if not exists `otc`.`GJ_OTC_SEEK_ORDER` (
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(60) binary not null,
	`FUND_ACCOUNT` VARCHAR(60) binary not null,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(19, 0),
	`TRANSFER_TIME` DATETIME,
	`PRO_NAME` VARCHAR(60) binary,
	`PRO_CODE` VARCHAR(60) binary,
	`PRO_NUM` VARCHAR(60) binary,
	`ORDER_QTY` NUMERIC(19, 0),
	`ORDER_PRICE` NUMERIC(19, 4),
	`BUY_RATE` NUMERIC(19, 5),
	`ORDER_STATUS` VARCHAR(3) binary,
	`TRANSFER_ORDER_NUM` VARCHAR(60) binary,
	`SOURCE` VARCHAR(2) binary,
	`CID` VARCHAR(12) binary,
	`CUST_NAME` VARCHAR(60) binary,
	`CUST_ADDRESS` VARCHAR(60) binary,
	`TGLJ_INFO` VARCHAR(306) binary,
	constraint `BIN$JRvB0lkX0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='求购订单 意向买单';

create table if not exists `otc`.`GJ_G3020_CUSTOMER_VOTING_INFO` (
	`ID` NUMERIC(19, 0) not null,
	`CYCLE_CODE` VARCHAR(10) binary not null,
	`PROD_CODE` VARCHAR(24) binary not null,
	`CUST_NUM` VARCHAR(24) binary not null,
	`RD_DIRECTION` VARCHAR(3) binary not null,
	`VOTE_DATE` DATETIME,
	`EXPECT_RATE` VARCHAR(24) binary,
	`TARGET_TYPE` VARCHAR(3) binary not null,
	`JYB_FLAG` VARCHAR(2) binary,
	`MOBILE` VARCHAR(24) binary,
	`PROD_TARGET_ID` VARCHAR(24) binary,
	constraint `BIN$JRvB0ldS0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='客户投票信息';

create table if not exists `otc`.`G2021_INVEST_PROD_FEATURE` (
	`ID` VARCHAR(39) binary not null,
	`PROD_ID` VARCHAR(39) binary,
	`TID` VARCHAR(39) binary,
	`FEATURE` VARCHAR(306) binary,
	`PRIORITY` NUMERIC(38, 0),
	constraint `BIN$JRvB0lSE0lrgYAB/AQBj0w==$0` primary key (`ID`)
);

create table if not exists `otc`.`GJ_G2010_PROD_INFO_BASE_DUIB` (
	`PROD_CODE` VARCHAR(36) binary not null,
	`PROD_NAME` VARCHAR(120) binary,
	`SHT_NAME` VARCHAR(120) binary,
	`PROD_TYPE` VARCHAR(3) binary,
	`RATE` NUMERIC(19, 6),
	`PROD_LABEL` VARCHAR(36) binary,
	`PROD_DAY` VARCHAR(36) binary,
	`RISK_TYPE` VARCHAR(36) binary,
	`INVEST_TYPE` VARCHAR(36) binary,
	`DAY_ADD` NUMERIC(19, 6),
	`NEW_NAV` NUMERIC(19, 6),
	`ONE_NAV` NUMERIC(19, 6),
	`ACC_NET` NUMERIC(19, 6),
	`UNIT_YLD_RMB` NUMERIC(19, 6),
	`RATE_1Y` NUMERIC(19, 6),
	`EXP_RATE_PER_SEVENDAY` NUMERIC(19, 6),
	`FUND_RANK_1Y` VARCHAR(36) binary,
	`REF_START_DATE` VARCHAR(10) binary,
	`REF_END_DATE` VARCHAR(10) binary,
	`MOST_ORIGIN_MONEY` NUMERIC(19, 2),
	`ORIGIN_MONEY` NUMERIC(19, 2),
	`ADD_MONEY` NUMERIC(19, 2),
	`PRODPRE_RATIO` NUMERIC(19, 6),
	`LEAVE_MONEY` VARCHAR(36) binary,
	`PROD_DETAIL` VARCHAR(36) binary,
	`PROD_DETAIL_MORE` VARCHAR(36) binary,
	`SELL_1W` NUMERIC(19, 0),
	`SELL_15D` NUMERIC(19, 0),
	`SELL_1M` NUMERIC(19, 0),
	`SELL_3M` NUMERIC(19, 0),
	`SELL_6M` NUMERIC(19, 0),
	`SELL_1Y` NUMERIC(19, 0),
	`COMM_1W` NUMERIC(19, 6),
	`COMM_15D` NUMERIC(19, 6),
	`COMM_1M` NUMERIC(19, 6),
	`COMM_3M` NUMERIC(19, 6),
	`COMM_6M` NUMERIC(19, 6),
	`COMM_1Y` NUMERIC(19, 6),
	`KEY` VARCHAR(3) binary,
	`SUB_STA` VARCHAR(4) binary,
	`REF_STA` VARCHAR(4) binary,
	`SELL_STA` VARCHAR(4) binary,
	`RED_STA` VARCHAR(4) binary,
	`TRANS_STA` VARCHAR(4) binary,
	`FIX_BUY_STA` VARCHAR(4) binary,
	`CANCEL_TRANS_STA` VARCHAR(4) binary,
	`ID` NUMERIC(19, 0),
	`NO_OPEN_KEY` VARCHAR(3) binary,
	`PROD_ID` VARCHAR(60) binary,
	`COMM_3Y` NUMERIC(19, 6),
	`BUY_STATUS` VARCHAR(3) binary,
	`COMM` NUMERIC(19, 6),
	`COMM_YEAR` NUMERIC(19, 6),
	`PRO_PROVIDER` VARCHAR(60) binary,
	`SUP_NAME` VARCHAR(120) binary,
	`G_BEGIN_DATE` NUMERIC(8, 0),
	`G_END_DATE` NUMERIC(8, 0),
	`NET_VALUE_TYPE` NUMERIC(19, 0),
	`PROD_BEGIN_DATE` VARCHAR(12) binary,
	`STOCK_CODE` VARCHAR(120) binary,
	`INV_OBJ` VARCHAR(2160) binary,
	`INV_RAN` VARCHAR(2400) binary,
	`BIZDATE` VARCHAR(10) binary,
	`FOUND_DATE` VARCHAR(12) binary,
	`MANAGE_FEE` NUMERIC(19, 6),
	`FUND_TRU_FEE` NUMERIC(19, 6),
	`INCOME_TYPE` VARCHAR(2) binary,
	`TRUSTEE_BANK` VARCHAR(120) binary,
	`DATA_SOURCE` VARCHAR(3) binary,
	`NAV_DATE` VARCHAR(10) binary,
	`COMM_2Y` NUMERIC(18, 9),
	`NEXT_OPEN_DAY` DATETIME,
	`OPEN_DAY` DATETIME,
	`PRO_EXP` VARCHAR(1200) binary,
	`INV_MNG` VARCHAR(1200) binary,
	`PY_NAME` VARCHAR(60) binary,
	`ACT_MAX_SCALE` NUMERIC(19, 6),
	`AUTOBUYFLAG` VARCHAR(3) binary,
	`PRODPRE_RATIO1` VARCHAR(60) binary,
	`MAX_SUBSCRIBE_NUM` NUMERIC(19, 0),
	`NEXT_PRODPRE_RATIO` NUMERIC(19, 6),
	`PHASE` VARCHAR(24) binary,
	`DT_COMM_1Y` NUMERIC(19, 6),
	`DT_COMM_2Y` NUMERIC(19, 6),
	`DT_COMM_3Y` NUMERIC(19, 6),
	`DT_COMM_5Y` NUMERIC(19, 6),
	`XS_STATUS` VARCHAR(2) binary,
	`STL_RISK_TYPE` VARCHAR(12) binary,
	`PRO_KIND` VARCHAR(3) binary,
	`PRO_TERM` VARCHAR(3) binary,
	`PRO_VIDEO` VARCHAR(3) binary,
	`RISK_APPETITE` VARCHAR(3) binary,
	`PRO_CTRLKIND` VARCHAR(12) binary,
	`PRO_PCTRLKINDS` VARCHAR(24) binary,
	`PPROFEINVEST` VARCHAR(24) binary,
	`PMINLEVEL` VARCHAR(3) binary,
	`PRO_BUYFLOW` VARCHAR(3) binary,
	`CALMHOURS` VARCHAR(6) binary,
	`EXTQTY1` NUMERIC(19, 0),
	`PROD_MAX_BALA` NUMERIC(19, 2),
	`ASSESS_LEVEL` VARCHAR(36) binary,
	`PROD_SPONSOR` VARCHAR(120) binary,
	`IPO_BEGIN_DATE` VARCHAR(12) binary,
	`IPO_END_DATE` VARCHAR(12) binary,
	`INCOME_TYPE_OTC` VARCHAR(2) binary,
	`INST_ID` VARCHAR(36) binary,
	`EXP_RETURNRATE` VARCHAR(600) binary,
	`RISK_LVL_OTC` VARCHAR(3) binary,
	`MINSIZE` NUMERIC(19, 2),
	`PRODSUB_RATE` NUMERIC(19, 8),
	`MIN_SHARE` NUMERIC(19, 2),
	`ORG_LOWLIMIT_BALANCE` NUMERIC(19, 2),
	`MIN_SHARE2` NUMERIC(19, 2),
	`ORG_LOWLIMIT_BALANCE2` NUMERIC(19, 2),
	`ORG_APPEND_BALANCE2` NUMERIC(19, 2),
	`ALLOT_LIMITSHARE2` NUMERIC(19, 2),
	`ECONTRACT_TYPE` VARCHAR(3) binary,
	`PROD_STAT` VARCHAR(12) binary default 1,
	`PRODTA_NO` VARCHAR(12) binary,
	`ORG_APPEND_BALANCE` NUMERIC(19, 2),
	`PROD_MANAGER` VARCHAR(120) binary,
	`PROD_TRUSTEE` VARCHAR(120) binary,
	`TOSOURCE` VARCHAR(2) binary,
	`HQB_STATUS` VARCHAR(2) binary default 2,
	`TBLX` VARCHAR(120) binary
);

create table if not exists `otc`.`GJ_G2010_ITEM_INFO1` (
	`ID` NUMERIC(20, 0) not null,
	`ITEM_CODE` VARCHAR(10) binary not null,
	`ITEM_NAME` VARCHAR(120) binary,
	`ITEM_REMARK` VARCHAR(240) binary,
	`ITEM_URL` VARCHAR(1200) binary,
	`ITEM_TYPE` CHAR(1) binary,
	`AUDIT_STATUS` CHAR(1) binary,
	`PRIORITY` NUMERIC(8, 0),
	`ITEM_CODE_SUPER` VARCHAR(10) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPD_TIME` DATETIME,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`ITEM_STATUS` CHAR(1) binary,
	`TOP_ADVERTISE_NAME` VARCHAR(24) binary,
	`TOP_ADVERTISE_TIME` VARCHAR(12) binary,
	`TOP_ADVERTISE_DISPLAY_TYPE` CHAR(1) binary,
	`NOTICE_DISPLAY_TIME` VARCHAR(12) binary,
	`SECOND_ITEM_STYLE` CHAR(1) binary,
	`SELL_REMIND` CHAR(1) binary,
	`LOGO_URL` VARCHAR(600) binary,
	`NOTICE_DISPLAY_TYPE` CHAR(1) binary,
	`LOGO_IMG_NAME` VARCHAR(240) binary,
	`LOGO_IMG_ID` VARCHAR(240) binary,
	`LOGO_IMG_SOURCE_NAME` VARCHAR(60) binary,
	`MORE_TYPE` CHAR(1) binary,
	`OPER_ID` VARCHAR(60) binary,
	`UPD_RECORD` VARCHAR(1200) binary,
	`MORE_TYPE_ID` VARCHAR(10) binary,
	`NOLOGIN_IS_DISPLAY` VARCHAR(3) binary,
	`TICKET_NUM` VARCHAR(60) binary,
	`MORE_WORD` VARCHAR(60) binary,
	`CUSTOMIZATION` VARCHAR(24) binary,
	`DEPT_NUM` NUMERIC(19, 0),
	`ORG_NUM` NUMERIC(19, 0),
	`ITEM_URL_OLD` VARCHAR(1200) binary,
	`MALL_URL` VARCHAR(1200) binary,
	`ITEM_PURPOSE` VARCHAR(24) binary,
	`POSITION_IS_DISPLAY` VARCHAR(3) binary,
	`EXPIRATION_IS_DISPLAY` VARCHAR(3) binary,
	`ITEM_PURPOSE_SHOW` VARCHAR(120) binary,
	`LOGIN_TO_JUMP` VARCHAR(3) binary default 2,
	`QUALIF_INVESTOR_JUMP` VARCHAR(3) binary default 0,
	`SHELF_TYPE` VARCHAR(3) binary,
	`ITEM_NS_IS_DISPLAY` VARCHAR(3) binary,
	`SHELF_BROWSE_WAY` VARCHAR(3) binary,
	`SHELF_IS_CARIYSEL` VARCHAR(3) binary,
	`SHELF_CARIYSEL_TIME` VARCHAR(3) binary,
	`PROD_WITH_ENHANCED` VARCHAR(3) binary,
	`NAME_DESCRI_DISPLACE` VARCHAR(3) binary,
	`LIMIT_SHOW_BAR` VARCHAR(3) binary,
	`BUY_BUTTON_SHOW` VARCHAR(3) binary,
	`MOULD_CODE` VARCHAR(24) binary,
	`SPARE_MOULD_CODE` VARCHAR(24) binary,
	`MOULD_CALCULATE_DATE` DATETIME,
	`ITEM_SUPER_PURPOSE` VARCHAR(3) binary,
	`ANOTHER_BATCH` VARCHAR(3) binary,
	`BUY_BUTTON_URL` VARCHAR(600) binary,
	`ICON_AFTER_URL` VARCHAR(600) binary,
	`ICON_AFTER_ID` VARCHAR(120) binary,
	`ICON_AFTER_NAME` VARCHAR(120) binary,
	`ANOTHER_BATCH_WORD` VARCHAR(24) binary,
	`USER_RULE_ID` VARCHAR(24) binary,
	`BLACK_ICON_URL` VARCHAR(600) binary,
	`BLACK_ICON_ID` VARCHAR(120) binary,
	`BLACK_ICON_NAME` VARCHAR(120) binary,
	`BLACK_ICON_AFTER_URL` VARCHAR(600) binary,
	`BLACK_ICON_AFTER_ID` VARCHAR(120) binary,
	`BLACK_ICON_AFTER_NAME` VARCHAR(120) binary,
	`USER_RULE_ID_SPARE` VARCHAR(24) binary,
	`ITEM_UUID` VARCHAR(60) binary,
	`PC_LOGO_URL` VARCHAR(600) binary,
	`PC_LOGO_ID` VARCHAR(120) binary,
	`PC_LOGO_NAME` VARCHAR(120) binary,
	`PC_ITEM_URL` VARCHAR(1200) binary,
	`THIRD_ITEM_TYPE` VARCHAR(3) binary,
	`RED_POINT_DISPLAY` VARCHAR(3) binary,
	`AUTO_SORT_IDENTIF` VARCHAR(3) binary,
	`RATE_TYPE` VARCHAR(60) binary,
	`VERSION_NUM` VARCHAR(120) binary,
	`VERSION_NUM_SHOW` VARCHAR(120) binary,
	`BOTTEM_FLOAT_STYLE` VARCHAR(3) binary,
	`FLOAT_WORD` VARCHAR(72) binary,
	`APP_FLOAT_URL` VARCHAR(600) binary,
	`JHW_FLOAT_URL` VARCHAR(600) binary,
	`PC_FLOAT_URL` VARCHAR(600) binary,
	`IS_ENABLE` VARCHAR(3) binary,
	`AGGREG_NAME` VARCHAR(24) binary,
	`AGGREG_REMARK` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_ID` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_SOURCE` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_URL` VARCHAR(600) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary
);

create table if not exists `otc`.`FUND_MANAGE_OPINION_SH` (
	`PERSONCODE` VARCHAR(306) binary comment '基金经理代码',
	`CREATE_DATE` DATETIME comment '创建日期',
	`UPDATE_DATE` DATETIME comment '更新日期',
	`CREATE_PERSONNEL` VARCHAR(60) binary comment '创建人',
	`UPDATE_PERSONNEL` VARCHAR(60) binary comment '更新人',
	`TITLE` VARCHAR(306) binary comment '标题',
	`EXCERPT` VARCHAR(1200) binary comment '文章摘要',
	`LINK` VARCHAR(600) binary comment '链接',
	`TIME` DATETIME comment '发布时间',
	`SOURCE` VARCHAR(120) binary comment '来源',
	`AUDIT_STATUS` VARCHAR(3) binary comment '审核状态(1：审核通过，2：待审核，3：审核不通过，4,新增待审核，5：删除待审核)',
	`TEXT` LONGTEXT comment '正文',
	`ID` VARCHAR(306) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary comment '审核状态(1：审核通过，2：待审核，3：审核不通过，4,新增待审核，5：删除待审核)',
	`STATUS` VARCHAR(3) binary comment '状态：（0：无效，1：有效）',
	`TEXT_STRUCTURE` VARCHAR(3) binary comment '文本结构: (1：评论（默认），2：回复)',
	`CONTENT_TYPE` VARCHAR(3) binary comment '内容类型:(1：图文（默认），2：短视频)',
	`LINK_TEXT` VARCHAR(306) binary comment '跳连文字',
	`IMAGE_NAME1` VARCHAR(60) binary comment '配图1名字',
	`IMAGE_URL1` VARCHAR(240) binary comment '配图1地址',
	`IMAGE_ID1` VARCHAR(120) binary comment '配图1ID',
	`IMAGE_NAME2` VARCHAR(60) binary comment '配图2名字',
	`IMAGE_URL2` VARCHAR(240) binary comment '配图2地址',
	`IMAGE_ID2` VARCHAR(120) binary comment '配图2ID',
	`IMAGE_NAME3` VARCHAR(60) binary comment '配图3名字',
	`IMAGE_URL3` VARCHAR(240) binary comment '配图3地址',
	`IMAGE_ID3` VARCHAR(120) binary comment '配图3ID',
	`IMAGE_NAME4` VARCHAR(60) binary comment '配图4名字',
	`IMAGE_URL4` VARCHAR(240) binary comment '配图4地址',
	`IMAGE_ID4` VARCHAR(120) binary comment '配图4ID',
	`IMAGE_NAME5` VARCHAR(60) binary comment '配图5名字',
	`IMAGE_URL5` VARCHAR(240) binary comment '配图5地址',
	`IMAGE_ID5` VARCHAR(120) binary comment '配图5ID',
	`TRD_CODE` VARCHAR(1200) binary comment '在管产品',
	`OPEN_CIRCLE_REVIEW` VARCHAR(3) binary comment '开放圈子评论：（1：开放（默认），0：不开放）',
	`TOP_VIEW` VARCHAR(3) binary comment '置顶观点：（1：置顶，0：不置顶（默认））',
	`SEND_STATUS` VARCHAR(3) binary default 0 comment '推送状态：（0：未推送，1：已推送，2：删除）',
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_OTC_MALLTRADE_STOCKCAN_LS` (
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(24) binary not null,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(24) binary,
	`FUND_ACCOUNT` VARCHAR(24) binary,
	`ENTRUST_NO` VARCHAR(24) binary,
	`INIT_DATE` VARCHAR(10) binary,
	`ENTRUST_INFO` VARCHAR(24) binary,
	`STOCK_NAME` VARCHAR(24) binary,
	`STOCK_CODE` VARCHAR(24) binary,
	`CANCEL_TIME` VARCHAR(24) binary
)
comment='股票/ETF基金撤单流水';

create table if not exists `otc`.`GJ_G2050_CANCEL_ORDER` (
	`ID` NUMERIC(20, 0),
	`ALLOT_NO` VARCHAR(60) binary,
	`ENTRUST_DATE` VARCHAR(24) binary,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`BUSIN_ACCOUNT` VARCHAR(60) binary,
	`SECUM_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(20, 0),
	`PRO_NAME` VARCHAR(60) binary,
	`PROD_CODE` VARCHAR(60) binary,
	`CANCEL_TIME` DATETIME(6),
	`ENTRUST_BALANCE` NUMERIC(20, 0),
	`SERIAL_NO` NUMERIC(20, 0),
	`PROD_TYPE_CHILD` VARCHAR(12) binary
)
comment='私募基金订单取消';

create table if not exists `otc`.`GJ_G9010_PRO_LST` (
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`PROJECT_NUM` VARCHAR(36) binary not null,
	`PROJECT_NAME` VARCHAR(60) binary,
	`PROJECT_URL` VARCHAR(240) binary,
	`PROJECT_REMARK` VARCHAR(2400) binary,
	`PROJECT_STATUS` VARCHAR(3) binary,
	`EXP_BEGIN_DATE` DATETIME,
	`EXP_END_DATE` DATETIME,
	`ACT_BEGIN_DATE` DATETIME,
	`ACT_END_DATE` DATETIME,
	`PROJECT_LEADER` VARCHAR(36) binary,
	`OTHER_PERSON` VARCHAR(36) binary,
	`VERSION` VARCHAR(36) binary,
	constraint `BIN$JRvB0leC0lrgYAB/AQBj0w==$0` primary key (`PROJECT_NUM`)
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_TIME_CNT` (
	`YMD` VARCHAR(10) binary not null comment '日期',
	`PRO_TYPE` CHAR(1) binary not null comment '产品种类(1:新客产品A  2：新客产品B  3：新客产品C)',
	`SOURCE` CHAR(1) binary not null comment '来源',
	`CNT1` NUMERIC(19, 0) comment '9:00-9:15',
	`CNT2` NUMERIC(19, 0) comment '9:15-9:30',
	`CNT3` NUMERIC(19, 0) comment '9:30-9:45',
	`CNT4` NUMERIC(19, 0) comment '9:45-10:00',
	`CNT5` NUMERIC(19, 0) comment '10:00-10:15',
	`CNT6` NUMERIC(19, 0) comment '10:15-10:30',
	`CNT7` NUMERIC(19, 0) comment '10:30-10:45',
	`CNT8` NUMERIC(19, 0) comment '10:45-11:00',
	`CNT9` NUMERIC(19, 0) comment '11:00-11:15',
	`CNT10` NUMERIC(19, 0) comment '11:15-11:30',
	`CNT11` NUMERIC(19, 0) comment '11:30-11:45',
	`CNT12` NUMERIC(19, 0) comment '11:45-12:00',
	`CNT13` NUMERIC(19, 0) comment '12:00-12:15',
	`CNT14` NUMERIC(19, 0) comment '12:15-12:30',
	`CNT15` NUMERIC(19, 0) comment '12:30-12:45',
	`CNT16` NUMERIC(19, 0) comment '12:45-13:00',
	`CNT17` NUMERIC(19, 0) comment '13:00-13:15',
	`CNT18` NUMERIC(19, 0) comment '13:15-13:30',
	`CNT19` NUMERIC(19, 0) comment '13:30-13:45',
	`CNT20` NUMERIC(19, 0) comment '13:45-14:00',
	`CNT21` NUMERIC(19, 0) comment '14:00-14:15',
	`CNT22` NUMERIC(19, 0) comment '14:15-14:30',
	`CNT23` NUMERIC(19, 0) comment '14:30-14:45',
	`CNT24` NUMERIC(19, 0) comment '14:45-15:00',
	constraint `BIN$JRvB0lkD0lrgYAB/AQBj0w==$0` primary key (`YMD`, `PRO_TYPE`, `SOURCE`)
)
comment='新客产品认购时间分布新增';

create table if not exists `otc`.`GJ_G2020_FUNCTION_DAMPER_LIST` (
	`FUNCTION_ID` VARCHAR(10) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_G2010_TOPIC_STATISTICS` (
	`ID` VARCHAR(24) binary,
	`TOPIC_CODE` VARCHAR(60) binary,
	`TOPIC_NAME` VARCHAR(120) binary,
	`CUST_TELNUM` VARCHAR(2400) binary,
	`TOPIC_CASE` VARCHAR(24) binary,
	`VOTE_TIME` DATETIME
)
comment='话题投票';

create table if not exists `otc`.`GJ_G2010_ITEM_INFO_MB_PUB_SH` (
	`ID` NUMERIC(20, 0),
	`ITEM_CODE` VARCHAR(10) binary,
	`ITEM_NAME` VARCHAR(96) binary,
	`ITEM_REMARK` VARCHAR(240) binary,
	`ITEM_URL` VARCHAR(600) binary,
	`ITEM_TYPE` CHAR(1) binary,
	`AUDIT_STATUS` CHAR(1) binary,
	`PRIORITY` NUMERIC(8, 0),
	`ITEM_CODE_SUPER` NUMERIC(20, 0),
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPD_TIME` DATETIME,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`ITEM_STATUS` CHAR(1) binary,
	`TOP_ADVERTISE_NAME` VARCHAR(24) binary,
	`TOP_ADVERTISE_TIME` VARCHAR(12) binary,
	`TOP_ADVERTISE_DISPLAY_TYPE` CHAR(1) binary,
	`NOTICE_DISPLAY_TIME` VARCHAR(12) binary,
	`SECOND_ITEM_STYLE` CHAR(1) binary,
	`SELL_REMIND` CHAR(1) binary,
	`LOGO_URL` VARCHAR(600) binary,
	`NOTICE_DISPLAY_TYPE` CHAR(1) binary,
	`LOGO_IMG_NAME` VARCHAR(240) binary,
	`LOGO_IMG_ID` VARCHAR(240) binary,
	`LOGO_IMG_SOURCE_NAME` VARCHAR(60) binary,
	`MORE_TYPE` CHAR(1) binary,
	`OPER_ID` VARCHAR(60) binary,
	`UPD_RECORD` VARCHAR(1200) binary,
	`MORE_TYPE_ID` VARCHAR(10) binary,
	`MORE_WORD` VARCHAR(60) binary,
	`CUSTOMIZATION` VARCHAR(24) binary,
	`NOLOGIN_IS_DISPLAY` VARCHAR(3) binary,
	`TICKET_NUM` VARCHAR(60) binary,
	`ORG_NUM` NUMERIC(19, 0),
	`DEPT_NUM` NUMERIC(19, 0),
	`ITEM_URL_OLD` VARCHAR(1200) binary,
	`ITEM_PURPOSE` VARCHAR(24) binary,
	`MALL_URL` VARCHAR(600) binary,
	`POSITION_IS_DISPLAY` VARCHAR(3) binary,
	`ITEM_PURPOSE_SHOW` VARCHAR(120) binary,
	`EXPIRATION_IS_DISPLAY` VARCHAR(3) binary,
	`NEW_ORG_NUM` VARCHAR(1200) binary,
	`LOGIN_TO_JUMP` VARCHAR(3) binary,
	`QUALIF_INVESTOR_JUMP` VARCHAR(3) binary,
	`SHELF_TYPE` VARCHAR(3) binary,
	`ITEM_NS_IS_DISPLAY` VARCHAR(3) binary,
	`SHELF_BROWSE_WAY` VARCHAR(3) binary,
	`SHELF_IS_CARIYSEL` VARCHAR(3) binary,
	`SHELF_CARIYSEL_TIME` VARCHAR(3) binary,
	`PROD_WITH_ENHANCED` VARCHAR(3) binary,
	`NAME_DESCRI_DISPLACE` VARCHAR(3) binary,
	`LIMIT_SHOW_BAR` VARCHAR(3) binary,
	`BUY_BUTTON_SHOW` VARCHAR(3) binary,
	`MOULD_CODE` VARCHAR(24) binary,
	`SPARE_MOULD_CODE` VARCHAR(24) binary,
	`MOULD_CALCULATE_DATE` DATETIME,
	`ITEM_SUPER_PURPOSE` VARCHAR(3) binary,
	`ANOTHER_BATCH` VARCHAR(3) binary,
	`BUY_BUTTON_URL` VARCHAR(600) binary,
	`ICON_AFTER_URL` VARCHAR(600) binary,
	`ICON_AFTER_ID` VARCHAR(120) binary,
	`ICON_AFTER_NAME` VARCHAR(120) binary,
	`ANOTHER_BATCH_WORD` VARCHAR(24) binary,
	`USER_RULE_ID` VARCHAR(600) binary,
	`BLACK_ICON_URL` VARCHAR(600) binary,
	`BLACK_ICON_ID` VARCHAR(120) binary,
	`BLACK_ICON_NAME` VARCHAR(120) binary,
	`BLACK_ICON_AFTER_URL` VARCHAR(600) binary,
	`BLACK_ICON_AFTER_ID` VARCHAR(120) binary,
	`BLACK_ICON_AFTER_NAME` VARCHAR(120) binary,
	`USER_RULE_ID_SPARE` VARCHAR(600) binary,
	`ITEM_UUID` VARCHAR(60) binary,
	`PC_LOGO_URL` VARCHAR(600) binary,
	`PC_LOGO_ID` VARCHAR(120) binary,
	`PC_LOGO_NAME` VARCHAR(120) binary,
	`PC_ITEM_URL` VARCHAR(600) binary,
	`SUP_NAME` VARCHAR(60) binary,
	`PROD_FEATURE_LABEL_ENHANCED` VARCHAR(240) binary,
	`RED_POINT_DISPLAY` VARCHAR(3) binary,
	`THIRD_ITEM_TYPE` VARCHAR(3) binary,
	`AUTO_SORT_IDENTIF` VARCHAR(3) binary,
	`RATE_TYPE` VARCHAR(48) binary,
	`VERSION_NUM` VARCHAR(120) binary,
	`VERSION_NUM_SHOW` VARCHAR(120) binary,
	`BOTTEM_FLOAT_STYLE` VARCHAR(3) binary,
	`FLOAT_WORD` VARCHAR(72) binary,
	`APP_FLOAT_URL` VARCHAR(600) binary,
	`JHW_FLOAT_URL` VARCHAR(600) binary,
	`PC_FLOAT_URL` VARCHAR(600) binary,
	`IS_ENABLE` VARCHAR(3) binary,
	`AGGREG_NAME` VARCHAR(24) binary,
	`AGGREG_REMARK` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_ID` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_SOURCE` VARCHAR(240) binary,
	`SHARE_PIC_ON_MOBILE_URL` VARCHAR(600) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary,
	`YD_URL_NAME` VARCHAR(120) binary,
	`PC_URL_NAME` VARCHAR(120) binary,
	`JH_URL_NAME` VARCHAR(120) binary,
	`IS_FUNCTION` VARCHAR(3) binary,
	`FUNCTION_NAME` VARCHAR(120) binary,
	`SHARE_CODE` VARCHAR(20) binary,
	`SHARE_MINI_PROGRAM_WHETHER` VARCHAR(3) binary,
	`TEMPLATE_TYPE` VARCHAR(3) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`OUT_G2021_VIDEO_DOWNLOAD` (
	`VIDEO_ID` VARCHAR(306) binary comment ' 视频id ',
	`DATA_TIME` VARCHAR(24) binary comment ' 数据时间 ',
	`URL` VARCHAR(615) binary comment ' 视频url ',
	`TITLE` VARCHAR(306) binary comment ' 视频标题 ',
	`VIDEO_CODE` VARCHAR(306) binary comment ' 视频代码 ',
	`CREATE_TIME` VARCHAR(60) binary comment ' 创建时间 ',
	`STATUS` VARCHAR(3) binary comment '状态，0未下载，1下载成功',
	`SAVE_ADDRESS` VARCHAR(306) binary comment ' 保存地址  ',
	`FUND_CODE` VARCHAR(306) binary comment ' 产品代码 ',
	`TYPE` VARCHAR(3) binary comment '1:每季度同步的数据，2：每周同步的数据',
	`COVER_URL` VARCHAR(615) binary,
	`SHU_URL` VARCHAR(615) binary comment ' 竖版封面链接 ',
	`HENG_URL` VARCHAR(615) binary comment '横板封面',
	`SOURCE` VARCHAR(10) binary comment '来源'
);

create table if not exists `otc`.`GJ_G2020_FUND_CONVER_ORDER` (
	`BRANCH_NO` NUMERIC(5, 0) comment '分支机构',
	`CIF_ACCOUNT` VARCHAR(22) binary comment '一户通账户',
	`BUSIN_ACCOUNT` VARCHAR(22) binary comment '资金账户',
	`CLIENT_ID` VARCHAR(22) binary comment '应用系统客户编号',
	`FUND_CODE` VARCHAR(8) binary comment '转出基金',
	`FUND_COMPANY` VARCHAR(120) binary comment '基金公司代码',
	`TRANS_AMOUNT` VARCHAR(20) binary comment '转出份额',
	`TRANS_CODE` VARCHAR(8) binary comment '转入基金',
	`EXCEEDFLAG` VARCHAR(2) binary comment '巨额赎回标志',
	`REMARK` VARCHAR(306) binary comment '备注',
	`TGLJ_INFO` VARCHAR(306) binary comment '推广信息',
	`ENTRUST_NO` VARCHAR(10) binary comment '委托编号',
	`BUY_TIME` DATETIME comment '购买时间',
	`OP_REMARK` VARCHAR(2400) binary comment '业务状态',
	`BUSINESS_STATUS` VARCHAR(2) binary comment '成交编号',
	`BUSINESS_NO` VARCHAR(12) binary comment '成交编号',
	`INIT_DATE` NUMERIC(10, 0) comment '交易日期',
	`ENTRUST_BALANCE` NUMERIC(19, 2) comment '委托金额',
	`TSBZTYPE` VARCHAR(306) binary comment 'TSBZTYPE',
	`TSBZ` VARCHAR(306) binary comment 'TSBZ'
)
comment='基金转换订单';

create table if not exists `otc`.`GJ_OTC_CANCELL` (
	`ID` NUMERIC(20, 0) not null comment '主键ID',
	`INIT_DATE` NUMERIC(8, 0) not null comment '交易日期',
	`SERIAL_NO` NUMERIC(8, 0) not null comment '流水序号',
	`ALLOT_NO` VARCHAR(29) binary not null comment '申请编号',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` NUMERIC(19, 0) comment '营业部代码',
	`CANCELL_TIME` DATETIME comment '撤单时间',
	`PRO_NAME` VARCHAR(60) binary comment '产品名称',
	`PRO_CODE` VARCHAR(60) binary comment '产品代码',
	`PRO_NUM` VARCHAR(60) binary comment '产品编号',
	`ENTRUST_BALANCE` NUMERIC(19, 2) comment '撤单金额',
	`ORDER_STATUS` VARCHAR(3) binary comment '订单状态',
	`CANCELL_SOURCE` CHAR(1) binary comment '撤单来源(1：转让市场  2：收益凭证)',
	`OTC_ACCOUNT` VARCHAR(60) binary comment '撤单数量',
	`BS_FLAG` VARCHAR(6) binary comment '买卖方向("买卖方向  HB0 意向买    HS0 意向卖 1B0 买成确认  1S0 卖成确认 OB0 定价买    OS0 定价卖 G10 报价回购  G11 报价续做  G30 提前购回  支持复选")',
	`SUB_BUSIN_ACCOUNT` VARCHAR(120) binary comment '子账号，只有在投顾otc下单的会有值',
	constraint `BIN$JRvB0lhz0lrgYAB/AQBj0w==$0` primary key (`ID`, `INIT_DATE`, `SERIAL_NO`, `ALLOT_NO`)
)
comment='买家撤单表';

create table if not exists `otc`.`TABLE_MANAGE` (
	`TABLE_CHINESE_NAME` VARCHAR(306) binary comment ' 表中文名 ',
	`TABLE_ENGLISH_NAME` VARCHAR(306) binary not null comment ' 英文名 ',
	`LEAD_CADRE` VARCHAR(600) binary comment ' 负责人 ',
	`GENRE` VARCHAR(600) binary comment ' 分类 ',
	`DESCRIBE` VARCHAR(2400) binary comment ' 描述 ',
	`CREATE_TIME` DATETIME comment ' 创建时间 ',
	`UPD_TIME` DATETIME comment ' 更新时间 ',
	`SOURCE` VARCHAR(306) binary comment ' 来源 ',
	`USER_ID` VARCHAR(306) binary comment ' 数据库用户 ',
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	constraint `BIN$JRvB0mBr0lrgYAB/AQBj0w==$0` primary key (`TABLE_ENGLISH_NAME`)
);

create table if not exists `otc`.`GJ_OTC_SIGN_LS` (
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`SIGN_TYPE` CHAR(1) binary,
	`CONTENT` VARCHAR(60) binary,
	`CODE` VARCHAR(60) binary,
	`STATUS` CHAR(1) binary,
	`SIGN_DATE` NUMERIC(8, 0),
	`USER_CODE` VARCHAR(22) binary,
	`CID` VARCHAR(24) binary,
	`TEL_NUM` VARCHAR(24) binary,
	constraint `BIN$JRvB0llP0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='签到流水表';

create table if not exists `otc`.`GJ_LOTTERY_LS_OLD` (
	`CUST_NUM` VARCHAR(24) binary comment '客户代码',
	`USER_CODE` VARCHAR(22) binary comment '用户代码',
	`CIF_ACCOUNT` VARCHAR(24) binary comment '一户通账号',
	`PROJECT_ID` VARCHAR(24) binary comment '项目ID',
	`PRIZE_NAME` VARCHAR(60) binary comment '奖品',
	`AWARD_FLAG` NUMERIC(1, 0) comment '奖品标识',
	`LOTTERY_AMOUNT` NUMERIC(8, 0) comment '中奖数量',
	`LOTTERY_TIME` DATETIME comment '抽奖日期',
	`PHONE_NUM` VARCHAR(24) binary comment '手机号码',
	`BIZ_TIME` DATETIME comment '业务日期',
	`SHARE_FLAG` VARCHAR(12) binary comment '共享区分'
)
comment='抽奖流水表';

create table if not exists `otc`.`GJ_G2010_NEWMALL_ORDERS` (
	`ID` NUMERIC(19, 0) not null,
	`INIT_DATE` NUMERIC(10, 0),
	`SERIAL_NO` NUMERIC(12, 0),
	`ALLOT_NO` VARCHAR(60) binary,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(19, 0),
	`BUY_TIME` DATETIME,
	`PRO_NAME` VARCHAR(120) binary,
	`PRO_CODE` VARCHAR(60) binary,
	`PRO_NUM` VARCHAR(60) binary,
	`ENTRUST_BALANCE` NUMERIC(19, 2),
	`ORDER_STATUS` VARCHAR(3) binary,
	`CID_SOURCE` VARCHAR(29) binary,
	`TYPE` CHAR(1) binary,
	`RESERVED` CHAR(1) binary,
	`REMARK` VARCHAR(600) binary,
	`BATCH_NO` VARCHAR(120) binary,
	`TGLJ_INFO` VARCHAR(2400) binary,
	`REGTEL` VARCHAR(16) binary,
	`UPDATE_TIME` DATETIME,
	`MATCHAMT` NUMERIC(22, 4),
	`UP_REMARK` VARCHAR(60) binary,
	`NAV` NUMERIC(22, 4),
	`MATCHQTY` NUMERIC(22, 4),
	`OUTBIZSNO` VARCHAR(615) binary,
	`TRADE_TYPE` VARCHAR(3) binary,
	`TSBZTYPE` VARCHAR(306) binary,
	`TSBZ` VARCHAR(306) binary,
	`QW_SRCNO` VARCHAR(120) binary default '',
	constraint `BIN$JRvB0lXo0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='基金订单表';

create table if not exists `otc`.`GJ_G2010_PROD_SELL_VOLUME_INFO` (
	`SELL_YEAR` VARCHAR(12) binary not null,
	`SELL_MONTH` VARCHAR(12) binary not null,
	`GMJJ_SELL` NUMERIC(19, 0),
	`ZG_SELL` NUMERIC(19, 0),
	`THB1_SELL` NUMERIC(19, 0),
	`THB2_SELL` NUMERIC(19, 0),
	`NJYH_SELL` NUMERIC(19, 0),
	`XYYH_SELL` NUMERIC(19, 0),
	`XK_SELL` NUMERIC(19, 0)
)
comment='理财频道产品销量统计表';

create table if not exists `otc`.`GJ_MON_PRO_NAV` (
	`PROD_CODE` VARCHAR(36) binary not null,
	`PROD_NAME` VARCHAR(120) binary,
	`NAV_DATE` VARCHAR(10) binary,
	`NEW_NAV` NUMERIC(19, 6),
	`BUY_STATUS` VARCHAR(3) binary,
	`INVEST_TYPE` VARCHAR(36) binary,
	`MON_DATE` DATETIME
);

create table if not exists `otc`.`GJ_G2010_DT_SERIAL_DATA` (
	`ID` NUMERIC(19, 0) not null comment '主键ID',
	`SERIAL_NO` VARCHAR(60) binary comment '流水序号',
	`BUSINESS_STATUS` VARCHAR(2) binary comment '订单状态("0"未处理 "1"处理中 "2"成功 "3"失败)',
	`BUSINESS_NO` VARCHAR(60) binary comment '委托编号',
	`ENTRUST_DATE` VARCHAR(12) binary comment '处理日期',
	`BUSIN_ACCOUNT` VARCHAR(22) binary comment '资金账户',
	`FUND_CODE` VARCHAR(8) binary comment '基金代码',
	`FUND_DATE` VARCHAR(12) binary comment '资金返还日(每月扣款日)',
	`BEGIN_DATE` VARCHAR(12) binary comment '起始日期',
	`END_DATE` VARCHAR(12) binary comment '到期日期',
	`BALANCE` VARCHAR(20) binary comment '发生金额',
	`ACTION_MODE` VARCHAR(2) binary comment '动作类型',
	`RATION_KIND` VARCHAR(2) binary comment '定投类型',
	`ORDER_STATUS` VARCHAR(2) binary not null comment '操作状态("1"下单 "2"销户)',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` VARCHAR(23) binary comment '营业部代码',
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`OP_REMARK` VARCHAR(600) binary comment '操作备注',
	`PAYORGAN_ID` VARCHAR(24) binary comment '支付机构编号',
	`BANK_NO` VARCHAR(24) binary comment '银行代码',
	`BANK_ACCOUNT` VARCHAR(60) binary comment '银行账号',
	`FIXED_TYPE` VARCHAR(2) binary comment '定投类型( 1：普通定投 2：跨行定投 3:策略定 4：预约入金 5：工资理财)',
	`BANK_NAME` VARCHAR(120) binary comment '银行名称',
	`TGLJ_INFO` VARCHAR(2400) binary comment '推广信息',
	`REGTEL` VARCHAR(16) binary comment '注册手机号码',
	`MATCH_AMT` NUMERIC(22, 7) comment '成交金额',
	`ORDER_AMT` NUMERIC(22, 0) comment '委托金额',
	`MOBILE` VARCHAR(306) binary comment '手机号',
	`NAME` VARCHAR(306) binary comment '姓名',
	`CUST_MANAGER` VARCHAR(306) binary comment 'CUST_MANAGER',
	`OPEN_TIME` NUMERIC(16, 0) comment 'OPEN_TIME',
	`DEP_NAME` VARCHAR(306) binary comment '分公司',
	`ORG_NAME` VARCHAR(306) binary comment '机构名称',
	`BUY_TIME` NUMERIC(16, 0) comment '购买时间',
	`BUY_DATE` NUMERIC(16, 0) comment '购买日期',
	`ORDER_CNT` NUMERIC(16, 0) comment '委托次数',
	`UPDATE_TIME` DATETIME,
	`TGLJ_USERCODE` VARCHAR(120) binary comment '推广usercode',
	`TGLJ_ACTIVITYCODE` VARCHAR(120) binary comment '活动码',
	`TGLJ_CHANNEL` VARCHAR(120) binary comment '渠道码类型',
	`TGLJ_CHANNELID` VARCHAR(120) binary comment '渠道码',
	`TGLJ_FUNCTYPE` VARCHAR(120) binary comment '功能吗类型',
	`TGLJ_FUNCID` VARCHAR(120) binary comment '功能码',
	`TGLJ_MATTYPE` VARCHAR(120) binary comment '素材码类型',
	`TGLJ_MATID` VARCHAR(120) binary comment '素材码',
	`TGLJ_CODE` VARCHAR(120) binary comment '推广人工号',
	`TGLJ_WORKID` VARCHAR(120) binary comment '手输工号',
	`TGLJ_UPDATE_TIME` DATETIME comment '推广码更新时间',
	`TGLJ_UPDATE_STATUS` VARCHAR(3) binary comment '推广信息更新状态',
	constraint `BIN$JRvB0lVV0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='理财频道定投流水表';

create table if not exists `otc`.`GJ_G1080_NUMBER_GIFT_DATA` (
	`ID` NUMERIC(19, 0) not null comment '主键ID',
	`ORDER_NO` VARCHAR(39) binary comment '订单编号',
	`CUST_CODE` VARCHAR(60) binary comment '客户代码',
	`TEL` VARCHAR(39) binary comment '手机号',
	`CIFT_NUMBER` NUMERIC(19, 0) comment '君元宝数量',
	`GIFT_TIME` DATETIME comment '日期',
	`ORDER_AMOUNT` VARCHAR(23) binary comment '订单金额',
	`MESSAGE` VARCHAR(600) binary comment '错误信息',
	constraint `BIN$JRvB0lUd0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='评价有礼积分 ';

create table if not exists `otc`.`GJ_G2050_FUNCTION_LIST` (
	`TYPE` VARCHAR(120) binary not null,
	`FUNCTION_ID` VARCHAR(120) binary not null,
	`FUNCTION_NAME` VARCHAR(120) binary,
	`T2_FUNCTION_REMARK` VARCHAR(240) binary,
	`REMARK` VARCHAR(2400) binary,
	`FUNCTION_TYPE` VARCHAR(120) binary,
	`REC_GEN_TIME` DATETIME(0),
	`REC_UPD_TIME` DATETIME(0),
	`VERSION_REMARK` VARCHAR(3) binary
)
comment='接口一览';

create table if not exists `otc`.`GJ_G1080_COMMENT_GIFT_DATA` (
	`ID` NUMERIC(19, 0) not null comment '主键ID',
	`PROD_NAME` VARCHAR(39) binary comment '产品名称',
	`ORDER_NO` VARCHAR(39) binary comment '订单编号',
	`ORDER_ACCOUNT` VARCHAR(22) binary comment '订单额度',
	`ORDER_DATE` DATETIME comment '订单日期',
	`COMMENT_STARS` VARCHAR(60) binary default NULL comment '评价星级(1~5)',
	`IMPRESS_LABEL` VARCHAR(120) binary comment '印象标签',
	`COMMENT_CONTENT` VARCHAR(600) binary comment '评价内容',
	`COMMENT_DATE` DATETIME comment '评价日期',
	`CID` VARCHAR(40) binary comment '评价来源',
	`COMMENT_STATUS` VARCHAR(41) binary default NULL comment '评价状态(‘1’:添加 ‘2’：撤单)',
	`ORDER_TYPE` VARCHAR(39) binary comment '订单类型',
	constraint `BIN$JRvB0lUZ0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='评价有礼流水数据 ';

create table if not exists `otc`.`FUND_MNG_INFO_SH` (
	`PERSONNAME` VARCHAR(120) binary,
	`PERSONNAME_PY` VARCHAR(120) binary,
	`PERSONCODE` VARCHAR(60) binary,
	`SEX` VARCHAR(5) binary,
	`DEGREE` VARCHAR(96) binary,
	`IMAGE_NAME` VARCHAR(60) binary,
	`IMAGE_URL` VARCHAR(240) binary,
	`IMAGE_EDIT_ID` VARCHAR(120) binary,
	`IMAGE_EDIT_NAME` VARCHAR(120) binary,
	`IMAGE_EDIT_URL` VARCHAR(240) binary,
	`PERSONAL_IMAGE_ID` VARCHAR(120) binary,
	`PERSONAL_IMAGE_NAME` VARCHAR(120) binary,
	`PERSONAL_IMAGE_URL` VARCHAR(240) binary,
	`BIRTHDATE` VARCHAR(60) binary,
	`DK_CERTIFICATION` VARCHAR(306) binary,
	`PERSON_LABEL` VARCHAR(306) binary,
	`MNG_TITLE` VARCHAR(120) binary,
	`COMPANYNAME` VARCHAR(240) binary,
	`COMPANYCODE` VARCHAR(60) binary,
	`SUP_NAME` VARCHAR(306) binary,
	`PRO_PROVIDER` VARCHAR(60) binary,
	`RESUME` LONGTEXT,
	`RESUME_EDIT` LONGTEXT,
	`INVEST_STRATEGY` LONGTEXT,
	`MANAGE_SCALE` VARCHAR(60) binary,
	`NATUREPOSTYEAR` VARCHAR(24) binary,
	`YIELDSINCES` VARCHAR(24) binary,
	`CIRCLE_COMPETENCY` VARCHAR(1200) binary,
	`UPDATE_DATE` DATETIME,
	`UPDATE_PERSONNEL` VARCHAR(60) binary,
	`AUDIT_STATUS` VARCHAR(12) binary comment '审核状态审核状态(1、审核通过 2、待审核  3、审核不通过)',
	`AWARD_INF` VARCHAR(600) binary,
	`TRD_CODE` VARCHAR(24) binary,
	`SELL_FLAG` VARCHAR(12) binary,
	`RECOMMEND_FLAG` VARCHAR(12) binary,
	`RECOMMEND_PRIORITY` NUMERIC(65, 30),
	`VIDEO_URL` VARCHAR(240) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`CUST_INFO_BASE` (
	`CUST_ID` VARCHAR(24) binary,
	`REAL_NAME` VARCHAR(120) binary,
	`BIRTHDAY` NUMERIC(65, 30),
	`SEX` CHAR(1) binary,
	`ASSET` NUMERIC(65, 30),
	`MOBILE` VARCHAR(240) binary,
	`BRHID` CHAR(4) binary,
	`CARD_NUM` VARCHAR(60) binary,
	`EMAIL` VARCHAR(60) binary,
	`FUND_ID` VARCHAR(120) binary,
	`OPEN_TIME` NUMERIC(20, 0),
	`ADDRESS` VARCHAR(600) binary
);

create table if not exists `otc`.`GJ_OTC_SIGN_SECOND_LS` (
	`ID` NUMERIC(19, 0) not null,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`SIGN_TYPE` VARCHAR(12) binary,
	`CONTENT` VARCHAR(12) binary,
	`SIGN_DATE` NUMERIC(8, 0),
	`SIGN_MONTH` VARCHAR(12) binary,
	`CID` VARCHAR(60) binary,
	`CUST_NUM` VARCHAR(60) binary
)
comment='签到二期流水表';

create table if not exists `otc`.`GJ_INDEX_FLUCTUATE_MANAGER` (
	`NAME` VARCHAR(77) binary comment '基金经理名称',
	`INDEX_DES` VARCHAR(600) binary comment '指数介绍',
	`UPLOAD_TIME` VARCHAR(20) binary comment '更新时间',
	`IMG_URL` VARCHAR(615) binary comment '基金经理头像url地址',
	`IMG_NAME` VARCHAR(306) binary comment '基金经理头像名称',
	`IMG_ID` VARCHAR(154) binary comment '基金经理头像id',
	`CREATE_PERSONNEL` VARCHAR(44) binary comment '创建人',
	`UPD_PERSONNEL` VARCHAR(44) binary comment '更新人',
	`ID` VARCHAR(24) binary not null comment '主键id',
	`MNG_TITLE` VARCHAR(306) binary comment '基金经理头衔',
	`TITLE` VARCHAR(615) binary comment '观点标题',
	`DESCRIBE` VARCHAR(1200) binary comment '观点描述',
	`INDEX_ID` VARCHAR(24) binary comment '指数挺举id',
	`PSN_ID` VARCHAR(24) binary comment '基金经理id',
	`MANUAL_TYPE` VARCHAR(3) binary comment '自定义头像 1:是，2：否',
	`OCCUPATION_NO` VARCHAR(77) binary comment '执业编号',
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP comment '创建时间',
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP comment '更新时间',
	constraint `BIN$JRvB0le10lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='指数挺举指数投教';

create table if not exists `otc`.`GJ_WORK_PERSON_INFO` (
	`STAFF_NAME` VARCHAR(24) binary comment '1:人力  2:项目',
	`TYPE` VARCHAR(3) binary
);

create table if not exists `otc`.`GJ_OTC_MALLTRADE_STOCKTRADE_LS` (
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(24) binary not null,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(24) binary,
	`FUND_ACCOUNT` VARCHAR(24) binary,
	`ENTRUST_BS` VARCHAR(12) binary,
	`STOCK_NAME` VARCHAR(24) binary,
	`STOCK_CODE` VARCHAR(24) binary,
	`STOCK_AMOUNT` VARCHAR(24) binary,
	`PRICE` VARCHAR(12) binary,
	`AMOUNT` VARCHAR(60) binary,
	`TRADE_DATE` VARCHAR(10) binary,
	`TRADE_TIME` VARCHAR(10) binary,
	`ENTRUST_NO` VARCHAR(24) binary,
	`ENTRUST_STATUS` VARCHAR(12) binary default 2,
	`ENTRUST_PROP` VARCHAR(12) binary default NULL
)
comment='股票/ETF/分级基金委托流水';

create table if not exists `otc`.`GJ_G2020_REDEEM_ORDERS` (
	`PROD_CODE` VARCHAR(24) binary comment '产品代码',
	`CUST_NUM` VARCHAR(48) binary comment '客户代码',
	`FUND_ACCOUNT` VARCHAR(48) binary comment '资金账号',
	`CIF_ACCOUNT` VARCHAR(48) binary comment '一户通账户',
	`DEP_NAME` VARCHAR(48) binary comment '分公司',
	`ORG_NAME` VARCHAR(48) binary comment '营业部代码',
	`REDEEM_BALANCE` NUMERIC(65, 30) comment '赎回份额',
	`REDEEM_FLAG` VARCHAR(3) binary comment '巨额赎回标志',
	`SERIAL_NO` VARCHAR(48) binary comment '流水号',
	`ENTRUST_NO` VARCHAR(48) binary comment '委托编号',
	`ENTRUST_DATE` VARCHAR(48) binary comment '委托日期',
	`BUSS_STATUS` VARCHAR(3) binary comment '业务状态 0未处理 1处理中 2成功 3失败',
	`OPER_TYPE` VARCHAR(3) binary comment '操作类型  1.赎回2.预约赎回',
	`BRANCH_NO` NUMERIC(5, 0) comment '分支机构',
	`PROD_NAME` VARCHAR(48) binary comment '产品名称',
	`PROD_TYPE` VARCHAR(48) binary comment '产品类型',
	`PROD_CHILD_TYPE` VARCHAR(12) binary comment '产品子类型',
	`TSBZTYPE` VARCHAR(306) binary comment 'TSBZTYPE',
	`TSBZ` VARCHAR(306) binary comment 'TSBZ',
	`SERIALNO` NUMERIC(65, 30) comment '自增序列，只用作同步ob'
)
comment='赎回订单信息';

create table if not exists `otc`.`PROD_INVEST_MODULE_CODE_MIDDLE` (
	`TRADEDATE` NUMERIC(19, 0),
	`MODULE_CODE` VARCHAR(24) binary not null,
	`MODULE_NAME` VARCHAR(24) binary not null,
	`ITEM_CODE` VARCHAR(24) binary,
	`UPDATE_PERSONNEL` VARCHAR(24) binary,
	`UPDATE_DATE` DATETIME,
	`ADD_STATUS` VARCHAR(3) binary,
	`IMAGE_URL` VARCHAR(600) binary,
	`IMAGE_ID` VARCHAR(120) binary,
	`IMAGE_NAME` VARCHAR(120) binary,
	`MODULE_EXPLAIN` VARCHAR(1200) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`CUSTPROD_RECOMMEND_ALG` (
	`CONT_REC_ALG_NO` VARCHAR(60) binary,
	`CONT_REC_ALG_NAME` VARCHAR(306) binary
);

create table if not exists `otc`.`OFORDER_240039` (
	`SERVERID` VARCHAR(24) binary not null,
	`OPERDATE` VARCHAR(24) binary,
	`OPERTIME` VARCHAR(24) binary,
	`ORDERDATE` VARCHAR(24) binary not null,
	`SNO` VARCHAR(24) binary not null,
	`CUSTID` NUMERIC(19, 0),
	`ORGID` NUMERIC(19, 0),
	`FUNDID` NUMERIC(19, 0),
	`BRHID` NUMERIC(19, 0),
	`TRANSACC` VARCHAR(24) binary,
	`OFCODE` VARCHAR(24) binary,
	`OFNAME` VARCHAR(24) binary,
	`TAACC` VARCHAR(240) binary,
	`TACODE` NUMERIC(19, 0),
	`TRDID` NUMERIC(19, 0),
	`CANCELFLAG` VARCHAR(3) binary,
	`STATUS` VARCHAR(3) binary,
	`DEALFLAG` VARCHAR(3) binary,
	`ERRINFO` VARCHAR(24) binary,
	`NAME` VARCHAR(24) binary,
	`ACCTYPE` VARCHAR(3) binary,
	`CUSTKIND` VARCHAR(3) binary,
	`CUSTGROUP` VARCHAR(3) binary,
	`FUNDKIND` VARCHAR(3) binary,
	`FUNDLEVEL` VARCHAR(3) binary,
	`FUNDGROUP` VARCHAR(3) binary,
	`BANKCODE` VARCHAR(24) binary,
	`MONEYTYPE` VARCHAR(3) binary,
	`ORDERQTY` NUMERIC(19, 2),
	`ORDERAMT` NUMERIC(19, 2),
	`ORDERPRICE` NUMERIC(19, 4),
	`REDEEMTYPE` VARCHAR(3) binary,
	`PREDATE` VARCHAR(24) binary,
	`HAVEMATCHQTY` NUMERIC(19, 2),
	`FRONTFEE` NUMERIC(19, 2),
	`BACKFEE` NUMERIC(19, 2),
	`CONFIRMEDAMT` NUMERIC(19, 2),
	`OTHEROFCODE` VARCHAR(240) binary,
	`OTHERTAACC` VARCHAR(240) binary,
	`OTHERTRANSACC` VARCHAR(240) binary,
	`OTHERORGID` VARCHAR(24) binary,
	`OTHERDBTID` VARCHAR(24) binary,
	`DIVIDMETHOD` VARCHAR(24) binary,
	`DIVIDRATIO` NUMERIC(19, 6),
	`DISCRATIO` NUMERIC(19, 8),
	`OLDSN` VARCHAR(240) binary,
	`OLDOPERDATE` VARCHAR(24) binary,
	`SHARECLASS` VARCHAR(3) binary,
	`TAVOUCHER` VARCHAR(240) binary,
	`FRZREASON` VARCHAR(3) binary,
	`FRZPERIOD` VARCHAR(24) binary,
	`OTHERSN` VARCHAR(240) binary,
	`VALIDDAYS` NUMERIC(19, 0),
	`AGENTID` VARCHAR(24) binary,
	`OPERID` VARCHAR(24) binary,
	`OPERWAY` VARCHAR(3) binary,
	`OPERORG` VARCHAR(24) binary,
	`OPERLEVEL` VARCHAR(3) binary,
	`NETADDR` VARCHAR(360) binary,
	`CHKOPER` VARCHAR(24) binary,
	`AGENTOPER` VARCHAR(24) binary,
	`REMARK` VARCHAR(240) binary,
	`DEALFLAG_OWN` VARCHAR(3) binary,
	constraint `BIN$JRvB0l980lrgYAB/AQBj0w==$0` primary key (`ORDERDATE`, `SNO`, `SERVERID`)
);

create table if not exists `otc`.`G_P_USER_JZJY_OFORDER` (
	`OPENTIME` VARCHAR(15) binary comment '发生时间',
	`ORDERDATE` VARCHAR(15) binary comment '委托交易日期',
	`CUSTID` VARCHAR(120) binary comment '客户代码',
	`FUNDID` VARCHAR(120) binary comment '资金帐号',
	`ORGID` VARCHAR(120) binary comment '机构编码',
	`BRHID` VARCHAR(120) binary comment '机构分支',
	`OFCODE` VARCHAR(120) binary comment '基金代码',
	`OFNAME` VARCHAR(120) binary comment '基金名称',
	`ORDERAMT` VARCHAR(120) binary comment '委托金额',
	`ORDERQTY` VARCHAR(120) binary comment '委托数量',
	`TRDID` VARCHAR(120) binary comment 'TRDID',
	`OPERWAY` VARCHAR(306) binary comment '操作方式',
	`SNO` VARCHAR(306) binary comment '交易请求流水号',
	`UPDATETIME` DATETIME comment '更新时间',
	`SENDDATE` VARCHAR(39) binary comment '消费发送日期',
	`SENDTIME` VARCHAR(39) binary comment '消息发送时间',
	`MSG_ID` VARCHAR(306) binary comment '消息ID',
	`DATAID` VARCHAR(24) binary comment 'DATAID'
)
comment='用户集中交易订单';

create table if not exists `otc`.`GJ_2019_MALL_WORK_STATISTICS` (
	`ID` NUMERIC(65, 30) not null,
	`FUNC_TYP` VARCHAR(36) binary,
	`FUNCTION` VARCHAR(240) binary,
	`STATUS` VARCHAR(12) binary,
	`WORKLOAD` NUMERIC(65, 30),
	`PV` NUMERIC(65, 30),
	`UV` NUMERIC(65, 30),
	`PERMEABILITY` VARCHAR(10) binary,
	`RETENTION_RATE` VARCHAR(10) binary,
	`ORDER_CNT` NUMERIC(65, 30),
	`ORDER_AMT` NUMERIC(65, 30),
	`PARTIC_CNT` NUMERIC(65, 30),
	`REMARK` VARCHAR(4800) binary,
	`WORK_TIME` VARCHAR(24) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	constraint `BIN$JRvB0lS/0lrgYAB/AQBj0w==$0` primary key (`ID`)
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_TRADE_CNT` (
	`YMD` VARCHAR(10) binary not null comment '日期',
	`CNT1` NUMERIC(19, 0),
	`CNT2` NUMERIC(19, 0),
	`CNT3` NUMERIC(19, 0),
	`CNT4` NUMERIC(19, 0),
	`CNT5` NUMERIC(19, 0),
	`CNT6` NUMERIC(19, 0),
	`CNT7` NUMERIC(19, 0),
	`CNT8` NUMERIC(19, 0),
	`CNT9` NUMERIC(19, 0),
	`CNT10` NUMERIC(19, 0),
	`CNT11` NUMERIC(19, 0),
	`CNT12` NUMERIC(19, 0),
	`CNT13` NUMERIC(19, 2),
	`CNT14` NUMERIC(19, 2),
	`CNT15` NUMERIC(19, 2),
	`CNT16` NUMERIC(19, 2),
	`CNT17` NUMERIC(19, 2),
	`CNT18` NUMERIC(19, 2),
	`CNT19` NUMERIC(19, 2),
	`CNT20` NUMERIC(19, 2),
	`CNT21` NUMERIC(19, 2),
	`CNT22` NUMERIC(19, 2),
	`CNT23` NUMERIC(19, 2),
	`CNT24` NUMERIC(19, 2)
)
comment='新客各产品销量统计';

create table if not exists `otc`.`GJ_G2010_PROD_TYPE_CHILD_INFO` (
	`PROD_TYPE` VARCHAR(3) binary,
	`PROD_TYPE_CHILD` VARCHAR(12) binary,
	`PROD_TYPE_CHILD_NAME` VARCHAR(306) binary,
	`PRIORITY` VARCHAR(12) binary
);

create table if not exists `otc`.`GJ_PROD_JH_PAGE_STAT_ALL` (
	`TRADEDATE` NUMERIC(65, 30) not null,
	`ITEM_NAME` VARCHAR(154) binary,
	`ITEM_CODE` VARCHAR(154) binary,
	`ITEM_TYPE` VARCHAR(154) binary,
	`PROVINCES` VARCHAR(154) binary,
	`SEX` VARCHAR(154) binary,
	`AGE_SEGMENT` VARCHAR(154) binary,
	`QTY` NUMERIC(65, 30),
	`QTY_ALL` NUMERIC(65, 30),
	`ANT_ALL` NUMERIC(65, 30),
	`ITEM_TYPE_SUPER` VARCHAR(154) binary,
	`ITEM_CODE_SUPER` VARCHAR(154) binary,
	`CNT` NUMERIC(65, 30)
);

create table if not exists `otc`.`JY_FUND_MANAGER_RULE` (
	`ID` NUMERIC(20, 0) not null,
	`JYFM_CODE` VARCHAR(24) binary,
	`RULE_CODE` VARCHAR(24) binary,
	`DESC_START` NUMERIC(8, 0),
	`BOLT_NUM` NUMERIC(8, 0),
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPDATE_TIME` DATETIME,
	`UPDATE_PERSONNEL` VARCHAR(24) binary
);

create table if not exists `otc`.`GJ_G2060_CUST_INFO` (
	`USERABLE_MONEY` VARCHAR(3) binary,
	`RISK_TYPE` VARCHAR(3) binary comment '1.0~1000 2.1000~50000  3.50000'
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_AMOUNT_CNT` (
	`YMD` VARCHAR(10) binary not null,
	`PRO_TYPE` CHAR(1) binary not null,
	`SOURCE` CHAR(1) binary not null,
	`CNT1` NUMERIC(19, 0),
	`CNT2` NUMERIC(19, 0),
	`CNT3` NUMERIC(19, 0),
	`CNT4` NUMERIC(19, 0),
	`CNT11` NUMERIC(19, 0),
	`CNT22` NUMERIC(19, 0),
	`CNT33` NUMERIC(19, 0),
	`CNT44` NUMERIC(19, 0),
	constraint `BIN$JRvB0ljQ0lrgYAB/AQBj0w==$0` primary key (`YMD`, `PRO_TYPE`, `SOURCE`)
)
comment='新客产品客户认购金额分布';

create table if not exists `otc`.`GJ_OTC_TRADE_REDEEM` (
	`INIT_DATE` NUMERIC(8, 0) not null,
	`SERIAL_NO` NUMERIC(8, 0) not null,
	`ALLOT_NO` VARCHAR(29) binary,
	`CLIENT_ID` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`SECUM_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(19, 0),
	`REDEEM_TIME` DATETIME,
	`REDEEM_BALANCE` NUMERIC(19, 2),
	`REDEEM_INFO` VARCHAR(306) binary,
	`BEGIN_DATE` NUMERIC(8, 0),
	`PRO_NAME` VARCHAR(120) binary,
	`PRO_CODE` VARCHAR(60) binary,
	`PRO_VALUE` NUMERIC(10, 2),
	`PRODTA_NO` VARCHAR(12) binary,
	`BUSINESS_STATUS` VARCHAR(3) binary,
	`SOURCE` CHAR(1) binary,
	constraint `BIN$JRvB0llz0lrgYAB/AQBj0w==$0` primary key (`INIT_DATE`, `SERIAL_NO`)
)
comment='客户赎回订单表';

create table if not exists `otc`.`GJ_OTC_TRANSFER_ORDER` (
	`REC_GEN_TIME` DATETIME(6) comment '创建日期',
	`REC_UPD_TIME` DATETIME(6) comment '更新日期',
	`ID` NUMERIC(19, 0) not null comment '主键id',
	`CUST_NUM` VARCHAR(60) binary not null comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary not null comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` NUMERIC(19, 0) comment '营业部代码',
	`BUY_TIME` DATETIME comment '入库时间',
	`TRANSFER_ORDER_NUM` VARCHAR(60) binary comment '转产品订单编号',
	`PRO_NAME` VARCHAR(60) binary comment '产品名称',
	`PRO_CODE` VARCHAR(60) binary comment '产品代码',
	`PRO_NUM` VARCHAR(60) binary comment '产品编号',
	`BUY_QTY` NUMERIC(19, 0) comment '转产品数量',
	`BUY_PRICE` NUMERIC(19, 4) comment '转产品价格',
	`ORDER_STATUS` VARCHAR(3) binary comment '订单状态',
	`ORDER_NUM` VARCHAR(60) binary comment '订单编号',
	`SOURCE` VARCHAR(2) binary comment '来源     1:PC端  2：移动端',
	`CID` VARCHAR(12) binary comment '订单来源渠道',
	`CUST_NAME` VARCHAR(60) binary comment '客户姓名',
	`CUST_ADDRESS` VARCHAR(60) binary comment '客户地址',
	`SERIAO_NO` VARCHAR(60) binary comment '流水号',
	`TGLJ_INFO` VARCHAR(306) binary comment '推广信息',
	constraint `BIN$JRvB0lmH0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='求购订单 确认卖单';

create table if not exists `otc`.`GJ_G2010_ITEM_MARKET_INFO_SH` (
	`ID` NUMERIC(19, 0) not null,
	`ITEM_CODE` VARCHAR(10) binary,
	`MARKET_NAME` VARCHAR(36) binary,
	`PRIORITY` NUMERIC(8, 0),
	`AUDIT_STATUS` CHAR(1) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPD_TIME` DATETIME,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`WEEKS` VARCHAR(240) binary,
	`TICKET_NUM` VARCHAR(60) binary,
	`NOLOGIN_IS_DISPLAY` VARCHAR(3) binary,
	`MALL_URL` VARCHAR(600) binary,
	`USER_RULE_ID` VARCHAR(600) binary,
	`PC_LINK` VARCHAR(600) binary,
	`BLACK_IMAGE_URL` VARCHAR(600) binary,
	`BLACK_IMAGE_ID` VARCHAR(120) binary,
	`BLACK_IMAGE_NAME` VARCHAR(120) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary,
	`YD_URL_NAME` VARCHAR(240) binary,
	`PC_URL_NAME` VARCHAR(240) binary,
	`JH_URL_NAME` VARCHAR(240) binary,
	`MARKETING_TAG` VARCHAR(15) binary,
	`XIAODIAN_LINK` VARCHAR(600) binary,
	`XIAODIAN_URL_NAME` VARCHAR(308) binary,
	`MARKET_IMG_URL` VARCHAR(600) binary,
	`MARKET_TYPE` CHAR(1) binary,
	`MARKET_START_TIME` DATETIME,
	`MARKET_END_TIME` DATETIME,
	`MARKET_IMG_NAME` VARCHAR(240) binary,
	`MARKET_IMG_ID` VARCHAR(240) binary,
	`PC_MARKET_URL` VARCHAR(600) binary,
	`PC_MARKET_ID` VARCHAR(120) binary,
	`PC_MARKET_NAME` VARCHAR(120) binary,
	`MARKET_REMARK` VARCHAR(600) binary,
	`OBJECT_TYPE` CHAR(1) binary,
	`IS_DISPLAY_OBJECT_NAME` CHAR(1) binary,
	`OBJECT_CODE` VARCHAR(60) binary,
	`BENCHMARK_TYPE` CHAR(1) binary,
	`IS_DISPLAY_BENCHMARK_NAME` CHAR(1) binary,
	`BENCHMARK_CODE` VARCHAR(60) binary,
	`PERIOD_TYPE` CHAR(1) binary,
	`MARKET_URL` VARCHAR(600) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_ROSE_CNT` (
	`YMD` VARCHAR(10) binary not null,
	`AMOUNT1` NUMERIC(19, 0),
	`AMOUNT2` NUMERIC(19, 0),
	`AMOUNT3` NUMERIC(19, 0),
	`AMOUNT4` NUMERIC(19, 0),
	`AMOUNT5` NUMERIC(19, 0),
	`AMOUNT6` NUMERIC(19, 0),
	`AMOUNT7` NUMERIC(19, 0),
	`AMOUNT8` NUMERIC(19, 0),
	`AMOUNT9` NUMERIC(19, 0),
	`SOURCE` CHAR(1) binary not null,
	`CNT1` VARCHAR(24) binary,
	`CNT2` VARCHAR(24) binary,
	`CNT3` VARCHAR(24) binary,
	`CNT4` VARCHAR(24) binary,
	`CNT5` VARCHAR(24) binary,
	`CNT6` VARCHAR(24) binary,
	constraint `BIN$JRvB0lju0lrgYAB/AQBj0w==$0` primary key (`YMD`, `SOURCE`)
)
comment='新客产品前日上周涨幅';

create table if not exists `otc`.`GJ_WORK_ATTENDENCE` (
	`NAME` VARCHAR(12) binary not null,
	`WORK_UID` VARCHAR(36) binary not null,
	`CARD_NO` VARCHAR(12) binary not null,
	`WORK_DAY` VARCHAR(120) binary not null,
	`ON_DUTY_TIME` VARCHAR(120) binary,
	`OFF_DUTY_TIME` VARCHAR(120) binary,
	`WORK_HOURS` VARCHAR(6) binary,
	`WORK_STATE` VARCHAR(10) binary
);

create table if not exists `otc`.`MNG_PFMANCE_LATEST_D` (
	`TRD_COE_D` VARCHAR(3600) binary comment '交易code',
	`EID` VARCHAR(72) binary comment '  编号',
	`MANAGER` VARCHAR(120) binary comment '基金经理',
	`PERSONCODE` VARCHAR(120) binary comment '人物代码',
	`TRD_CODE` VARCHAR(1800) binary comment '  在管基金代码',
	`UPDATEDATE` DATETIME comment '  更新日期',
	`YIELDSINCES` NUMERIC(20, 8) comment '  任职总回报',
	`RANKSINCE3Y` VARCHAR(120) binary comment '最近三年同类排名',
	`SECURITYTYPE` VARCHAR(120) binary comment '  在管基金类型',
	`YIELDSINCE3Y` NUMERIC(20, 8) comment '最近三年回报',
	`RANKSINCE2Y` VARCHAR(120) binary comment '最近两年同类排名',
	`YIELDSINCET` NUMERIC(20, 8) comment '  今年以来回报',
	`REMARK` VARCHAR(120) binary comment '  备注',
	`YIELDSINCEL1M` NUMERIC(20, 8) comment '  最近一月回报',
	`YIELDSINCEL3M` NUMERIC(20, 8) comment '  最近三月回报',
	`NATUREPOSTYEAR` NUMERIC(20, 8) comment '  自然任职年限',
	`RANKSINCET` VARCHAR(120) binary comment '今年以来同类排名',
	`YIELDSINCE1Y` NUMERIC(20, 8) comment '最近一年回报',
	`YIELDSINCE6M` NUMERIC(20, 8) comment '  最近六月回报',
	`RANKSINCE1Y` VARCHAR(120) binary comment '  最近一年同类排名',
	`YIELDSINCE2Y` NUMERIC(20, 8) comment '最近两年回报',
	`GEOYIELDA` NUMERIC(20, 8) comment '  几何任职年化总回报',
	`ACCUPOSTYEAR` NUMERIC(20, 8) comment '累计任职年限',
	`ESOURCEMEMO` VARCHAR(120) binary comment '来源',
	`EUTIME` DATETIME comment '资讯中心更新时间',
	`NUM` NUMERIC(1, 0) comment '数量',
	`YIELDSINCE1W` NUMERIC(65, 30) comment '最近一周回报',
	`SIMILAR_RANK_1W` NUMERIC(65, 30) comment '最近一周同类排名',
	`SIMILAR_RANK_3M` VARCHAR(60) binary comment '最近三月同类排名',
	`SIMILAR_RANK_1M` VARCHAR(60) binary comment '最近一月同类排名',
	`SIMILAR_RANK_6M` VARCHAR(60) binary comment '最近六月同类排名'
)
comment='基金经理';

create table if not exists `otc`.`GJ_G2050_RETURN_VISIT` (
	`ID` NUMERIC(20, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`BUSIN_ACCOUNT` VARCHAR(60) binary,
	`SECUM_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(20, 0),
	`PRO_NAME` VARCHAR(60) binary,
	`PROD_CODE` VARCHAR(60) binary,
	`PRO_NUM` VARCHAR(60) binary,
	`ENTRUST_DATE` VARCHAR(24) binary,
	`ORDER_QTY` NUMERIC(20, 0),
	`ORDER_PRICE` NUMERIC(20, 0),
	`ENTRUST_BALANCE` NUMERIC(20, 0),
	`ALLOT_NO` VARCHAR(60) binary,
	`REQUESTION_TIME` DATETIME(6),
	`BUY_RATE` NUMERIC(20, 0),
	`CUST_NAME` VARCHAR(60) binary comment '客户姓名',
	`CUST_ADDRESS` VARCHAR(60) binary comment '客户地址',
	`SERIAL_NO` NUMERIC(20, 0) comment '流水序号',
	`PROD_TYPE_CHILD` VARCHAR(12) binary,
	constraint `BIN$JRvB0lcL0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='私募基金回访表';

create table if not exists `otc`.`GJ_G2010_PROD_SELL_PUSH` (
	`TRADEDATE` NUMERIC(65, 30),
	`PROD_CODE` VARCHAR(120) binary comment '产品代码',
	`PROD_NAME` VARCHAR(120) binary,
	`SELL_AMT_MONTH_WEEK` NUMERIC(22, 4),
	`SELL_QTY_MONTH_WEEK` NUMERIC(22, 4),
	`SELL_AMT_MONTH_MONTH` NUMERIC(22, 4),
	`SELL_QTY_MONTH_MONTH` NUMERIC(22, 4),
	`WEEK_BEGIN_DATE` NUMERIC(19, 0),
	`MONTH_BEGIN_DATE` NUMERIC(19, 0),
	`END_DATE` NUMERIC(19, 0),
	`SELL_AMT_HALFMONTH` NUMERIC(22, 4),
	`SELL_QTY_HALFMONTH` NUMERIC(22, 4),
	`SELL_AMT_QUARTER` NUMERIC(22, 4),
	`SELL_QTY_QUARTER` NUMERIC(22, 4),
	`SELL_AMT_HALFYEAR` NUMERIC(22, 4),
	`SELL_QTY_HALFYEAR` NUMERIC(22, 4),
	`SELL_AMT_YEAR` NUMERIC(22, 4),
	`SELL_QTY_YEAR` NUMERIC(22, 4),
	`HALFMONTH_BEGIN_DATE` NUMERIC(19, 0),
	`QUARTER_BEGIN_DATE` NUMERIC(19, 0),
	`HALFYEAR_BEGIN_DATE` NUMERIC(19, 0),
	`YEAR_BEGIN_DATE` NUMERIC(19, 0),
	`PROD_TYPE` VARCHAR(3) binary,
	`PUSH_DATE` VARCHAR(10) binary
)
comment='销量排行';

create table if not exists `otc`.`GJ_OPEN_QUAL` (
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`REC_UPD_TIME` DATETIME(6) comment '记录更新时间',
	`ID` NUMERIC(19, 0) not null comment '主键id',
	`CUST_NUM` VARCHAR(60) binary not null comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary not null comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(19, 0),
	`OPEN_TIME` DATETIME,
	`OPEN_STATUS` VARCHAR(3) binary,
	constraint `BIN$JRvB0lhM0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='OTC交易权限开通表';

create table if not exists `otc`.`GJ_G2010_THB_SERIAL_DATA` (
	`ID` NUMERIC(19, 0) not null comment '主键ID',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` VARCHAR(23) binary comment '营业部代码',
	`EXCHANGE_TYPE` VARCHAR(5) binary comment '交易类别(1：天汇宝一号，2：天汇宝二号)',
	`STOCK_ACCOUNT` VARCHAR(36) binary comment '证券账号',
	`STOCK_CODE` VARCHAR(36) binary comment '证券代码',
	`PROD_CODE` VARCHAR(24) binary comment '产品代码',
	`EXPIRE_YEAR_RATE` VARCHAR(20) binary comment '到期年收益率',
	`ENTRUST_AMOUNT` VARCHAR(20) binary comment '委托数量',
	`ENTRUST_PROP` VARCHAR(4) binary comment '委托属性(QNE)',
	`ENTRUST_BS` VARCHAR(3) binary comment '买卖方向("天汇宝一号：1买入、2卖出天汇宝二号：报价回购")',
	`GT_BJHG_AUTOFLAG` VARCHAR(2) binary comment '报价回购是否自动续作("天汇宝一号：报价回购是否自动续作  ""0"":续作原期限 ""1"":不续作 ""2"":续作1天期 天汇宝二号：报价回购是否自动续作  ""1"":续作 ""0"":不续作")',
	`ENTRUST_NO` VARCHAR(36) binary comment '委托编号',
	`REPORT_NO` VARCHAR(36) binary comment '申请编号',
	`BATCH_NO` VARCHAR(36) binary comment '委托批号',
	`ORDER_STATUS` VARCHAR(2) binary not null comment '订单状态("1"下单 "0"提前赎回)',
	`REC_GEN_TIME` DATETIME(6) comment '（不知含义）',
	`ENTRUST_BALANCE` VARCHAR(20) binary comment '成交金额',
	`MOBILE` VARCHAR(24) binary comment '手机号',
	`OUT_WALLET_CODE` VARCHAR(60) binary comment '外部卡券',
	`PROD_NAME` VARCHAR(96) binary comment '产品名称',
	`CID_SOURCE` VARCHAR(24) binary comment '订单渠道 ',
	`TGLJ_INFO` VARCHAR(2400) binary comment '推广链接',
	`REGTEL` VARCHAR(16) binary comment '手机号',
	`KBN` VARCHAR(2) binary
)
comment='天汇宝二号表';

create table if not exists `otc`.`PROD_INVEST_MODULE_ZX_CODE` (
	`TRADEDATE` NUMERIC(19, 0),
	`MODULE_CODE` VARCHAR(24) binary,
	`MODULE_NAME` VARCHAR(24) binary
);

create table if not exists `otc`.`G2010_NEWMALL_ORDERS_OTC_ALL` (
	`ID` NUMERIC(65, 30) not null,
	`PRO_CODE` VARCHAR(60) binary not null,
	`PRO_NAME` VARCHAR(154) binary,
	`TYPE` CHAR(1) binary not null,
	`BUY_TIME` DATETIME(6),
	`ORDER_STATUS` VARCHAR(60) binary,
	`ALLOT_NO` VARCHAR(60) binary,
	`SERIAL_NO` VARCHAR(48) binary,
	`ENTRUST_BALANCE` NUMERIC(65, 30),
	`MATCHAMT` NUMERIC(65, 30),
	`REGTEL` VARCHAR(16) binary,
	`TGLJ_INFO` VARCHAR(2400) binary,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`UPDATE_TIME` DATETIME,
	`UP_REMARK` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`ORGID` NUMERIC(65, 30),
	`PRO_NUM` VARCHAR(60) binary,
	`CID_SOURCE` VARCHAR(29) binary,
	`REMARK` VARCHAR(2400) binary,
	`RESERVED` VARCHAR(2) binary,
	`INIT_DATE` NUMERIC(65, 30),
	`TGLJ_WORKID` VARCHAR(15) binary,
	`WORKID` VARCHAR(15) binary,
	`CODE` VARCHAR(15) binary,
	`STATUS` VARCHAR(3) binary,
	`CHANNEL` VARCHAR(154) binary,
	`TGLJ_CODE` VARCHAR(154) binary,
	`TGLJ_MATTYPE` VARCHAR(154) binary,
	`TGLJ_MATID` VARCHAR(154) binary,
	`TGLJ_CHANNELID` VARCHAR(154) binary,
	`TGLJ_FUNCTYPE` VARCHAR(154) binary,
	`TGLJ_TIMESTAMP` VARCHAR(154) binary,
	`TGLJ_FUNCID` VARCHAR(154) binary,
	`CAIJI_TYPE` VARCHAR(154) binary,
	`PUT_PEOPLE` VARCHAR(154) binary,
	`TGRWORKDEPNAME` VARCHAR(154) binary,
	`TGRWORKORGNAME` VARCHAR(154) binary,
	`TGRNAME` VARCHAR(154) binary,
	`PROD_TYPE_CHILD` VARCHAR(39) binary,
	`PROD_TYPE` VARCHAR(39) binary,
	`CUST_MANAGER` VARCHAR(154) binary,
	`DEP_NUM` VARCHAR(154) binary,
	`DEP_NAME` VARCHAR(154) binary,
	`ORG_NAME` VARCHAR(306) binary,
	`ORG_NUM` VARCHAR(154) binary,
	`MOBILE` VARCHAR(306) binary,
	`OPEN_TIME` VARCHAR(154) binary,
	`NAME` VARCHAR(77) binary,
	`TGRWORKDEPID` VARCHAR(39) binary,
	`TGRWORKORGID` VARCHAR(39) binary,
	constraint `BIN$JRvB0lRI0lrgYAB/AQBj0w==$0` primary key (`ID`, `PRO_CODE`, `TYPE`)
);

create table if not exists `otc`.`GJ_OTC_REPORT_XK_TIMET_CNT` (
	`YMD` VARCHAR(10) binary not null,
	`PRO_TYPE` CHAR(1) binary not null,
	`SOURCE` CHAR(1) binary not null,
	`CNTH1` NUMERIC(19, 0),
	`CNTH2` NUMERIC(19, 0),
	`CNTH3` NUMERIC(19, 0),
	`CNTH4` NUMERIC(19, 0),
	`CNTH5` NUMERIC(19, 0),
	`CNTH6` NUMERIC(19, 0),
	`CNTH7` NUMERIC(19, 0),
	`CNTH8` NUMERIC(19, 0),
	`CNTH9` NUMERIC(19, 0),
	`CNTH10` NUMERIC(19, 0),
	`CNTH11` NUMERIC(19, 0),
	`CNTH12` NUMERIC(19, 0),
	`CNTH13` NUMERIC(19, 0),
	`CNTH14` NUMERIC(19, 0),
	`CNTH15` NUMERIC(19, 0),
	`CNTH16` NUMERIC(19, 0),
	`CNTH17` NUMERIC(19, 0),
	`CNTH18` NUMERIC(19, 0),
	`CNTH19` NUMERIC(19, 0),
	`CNTH20` NUMERIC(19, 0),
	`CNTH21` NUMERIC(19, 0),
	`CNTH22` NUMERIC(19, 0),
	`CNTH23` NUMERIC(19, 0),
	`CNTH24` NUMERIC(19, 0),
	constraint `BIN$JRvB0lj60lrgYAB/AQBj0w==$0` primary key (`YMD`, `PRO_TYPE`, `SOURCE`)
);

create table if not exists `otc`.`INTERFACE_GATE_STATUS` (
	`ENV` VARCHAR(12) binary comment '环境： local、200、sit、uat',
	`STATUS` CHAR(1) binary comment '全局开关，0代表关闭，1代表打开',
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_OTC_MALLTRADE_FUND_LS` (
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(24) binary not null,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(24) binary,
	`FUND_ACCOUNT` VARCHAR(24) binary,
	`ENTRUST_NO` VARCHAR(24) binary,
	`TRADE_DATE` VARCHAR(10) binary,
	`TRADE_TIME` VARCHAR(10) binary,
	`FUND_COMPANY` VARCHAR(60) binary,
	`FUND_CODE` VARCHAR(60) binary,
	`FUND_NAME` VARCHAR(60) binary,
	`ENTRUST_FLAG` VARCHAR(12) binary,
	`BALANCE` VARCHAR(24) binary,
	`AMOUNT` VARCHAR(24) binary,
	`SERIAL_NO` VARCHAR(18) binary
)
comment='场内基金交易流水';

create table if not exists `otc`.`GJ_OTC_TRADE_BUY` (
	`INIT_DATE` NUMERIC(8, 0) not null comment '交易日期',
	`SERIAL_NO` NUMERIC(38, 0) not null comment '流水序号',
	`ALLOT_NO` VARCHAR(60) binary not null comment '申请编号',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`FUND_ACCOUNT` VARCHAR(60) binary comment '资金账户',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` NUMERIC(19, 0) comment '营业部代码',
	`BUY_TIME` DATETIME comment '购买时间',
	`PRO_NAME` VARCHAR(60) binary comment '产品名称',
	`PRO_CODE` VARCHAR(60) binary comment '产品代码',
	`PRO_NUM` VARCHAR(60) binary comment '产品编号',
	`ENTRUST_BALANCE` NUMERIC(19, 2) comment '委托金额',
	`ORDER_STATUS` VARCHAR(3) binary comment '订单状态',
	`ID` NUMERIC(20, 0) not null comment '主键ID',
	`OTC_ACCOUNT` VARCHAR(22) binary comment '一户通号',
	`SOURCE` CHAR(1) binary comment '来源',
	`EMP_ID` VARCHAR(24) binary comment '员工id',
	`CID` VARCHAR(120) binary comment '订单来源渠道',
	`REMARK` VARCHAR(2400) binary comment '备注',
	`TYPE` CHAR(1) binary comment '类型(1:收益凭证 2：专享客户)',
	`ORDER_TYPE` VARCHAR(3) binary comment '下单类型',
	`REGTEL` VARCHAR(16) binary comment '注册手机号码',
	`TGLJ_INFO` VARCHAR(2400) binary comment '推广信息',
	`UPDATE_TIME` DATETIME comment '更新日期',
	`MATCHAMT` NUMERIC(22, 4) comment '成交金额',
	`UP_REMARK` VARCHAR(60) binary comment '更新备注',
	`MATCHQTY` NUMERIC(22, 0) comment '成交数量',
	`OUTBIZSNO` VARCHAR(615) binary comment '外部号',
	`SUB_BUSIN_ACCOUNT` VARCHAR(120) binary comment '子账号，只有在投顾otc下单的会有值'
)
comment='买家订单表';

create table if not exists `otc`.`GJ_G2019_DATADICT_PROD` (
	`ID` VARCHAR(20) binary comment '主键ID',
	`PROD_TYPE` VARCHAR(20) binary comment '产品类型',
	`PROD_TYPE_NAME` VARCHAR(39) binary comment '产品类型名称',
	`PROD_TYPE_CHILD` VARCHAR(20) binary comment '产品子类型',
	`PROD_TYPE_CHILD_NAME` VARCHAR(39) binary comment '产品子类型名称'
)
comment='数据字典(产品类型-产品子类)(用于二级下拉框)';

create table if not exists `otc`.`G_P_USER_JZJY_OFCASHACCHA` (
	`SERVERID` VARCHAR(20) binary comment '服务ID',
	`SERIALNO` VARCHAR(20) binary comment '序列号',
	`CUSTID` VARCHAR(20) binary comment '客户代码',
	`ORGID` VARCHAR(10) binary comment '分公司(机构编码)',
	`BRHID` VARCHAR(10) binary comment '营业部(机构分支)',
	`FUNDID` VARCHAR(20) binary comment '资金账号',
	`TAACC` VARCHAR(39) binary comment '基金账号',
	`TRANSACC` VARCHAR(39) binary comment '交易账号',
	`ACCTYPE` VARCHAR(3) binary comment '账户类别',
	`TACODE` VARCHAR(3) binary comment 'ta编号',
	`OFCODE` VARCHAR(20) binary comment '基金代码',
	`SIGNSTATUS` VARCHAR(5) binary comment '签约状态',
	`FIRSTFLAG` VARCHAR(5) binary comment '是否完成是否扫单',
	`DEALDATE` VARCHAR(20) binary comment '处理日期',
	`SIGNDATE` VARCHAR(306) binary comment '签约日期',
	`NETADDR` VARCHAR(20) binary comment '网络地址',
	`REMARK` VARCHAR(1229) binary comment '备注',
	`THLJ_CHANNEL` VARCHAR(39) binary comment '推广渠道',
	`EMAIL` VARCHAR(39) binary comment '电子邮箱',
	`OPERID` VARCHAR(39) binary comment '签约柜员',
	`LOWAMT` VARCHAR(39) binary comment '客户保留最低金额',
	`CODERATIO` VARCHAR(39) binary comment '代码比例',
	`CANCELDATE` VARCHAR(20) binary comment '解约日期',
	`CANCELTIME` VARCHAR(20) binary comment '解约时间',
	`OPERWAY` VARCHAR(39) binary comment '操作方式',
	`OPERORG` VARCHAR(39) binary comment '开户机构',
	`FIRSTDATE` VARCHAR(20) binary comment '首次扫单日期',
	`DEALFLAG` VARCHAR(20) binary comment '处理状态',
	`SIGNTIME` VARCHAR(39) binary comment '签约时间',
	`SENDDATE` VARCHAR(39) binary comment '发送日期',
	`SENDTIME` VARCHAR(39) binary comment '发送时间',
	`tglj_channel` VARCHAR(154) binary,
	`DATAID` ROWID comment '数据ID',
	`UPDATETIME` DATETIME comment '更新时间',
	`CUST_NUM` VARCHAR(20) binary comment '客户代码',
	`MSG_ID` VARCHAR(306) binary comment '信息ID ',
	`TGLJ_CHANNEL` VARCHAR(154) binary comment 'tglj_channel'
)
comment='现金宝签约流水表';

create table if not exists `otc`.`CFH_JJGS_ITEM` (
	`NAME` VARCHAR(77) binary comment '基金公司名称2',
	`ITEM_CODE` VARCHAR(24) binary comment '栏目代码'
)
comment='栏目基金关系';

create table if not exists `otc`.`GJ_G2010_SECOND_ITEM_PRO_LS` (
	`ITEM_CODE` VARCHAR(10) binary not null,
	`PROD_CODE` VARCHAR(39) binary not null,
	`PROD_NAME` VARCHAR(72) binary,
	`AUDIT_STATUS` VARCHAR(3) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`STATUS` VARCHAR(3) binary not null,
	`UPD_TIME` DATETIME not null,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`OPER_ID` VARCHAR(60) binary,
	`PRIORITY` NUMERIC(8, 0) not null,
	`SOURCE` VARCHAR(12) binary not null,
	`PROD_STATUS` VARCHAR(2) binary comment '1:新增 2移除',
	constraint `BIN$JRvB0lZ10lrgYAB/AQBj0w==$0` primary key (`ITEM_CODE`, `SOURCE`, `STATUS`, `PRIORITY`, `PROD_CODE`, `UPD_TIME`)
);

create table if not exists `otc`.`GJ_G9010_PERSON_INFO` (
	`PERSON_ID` NUMERIC(2, 0) not null,
	`PERSON_NAME` VARCHAR(12) binary not null,
	constraint `BIN$JRvB0ld20lrgYAB/AQBj0w==$0` primary key (`PERSON_ID`)
);

create table if not exists `otc`.`GJ_PRO_PUBLICITY_MATERIALS` (
	`PRO_CODE` VARCHAR(77) binary comment '产品代码',
	`PRO_NAME` VARCHAR(308) binary comment '产品名称',
	`TYPE` VARCHAR(60) binary comment '宣传材料类型',
	`FILENAME` VARCHAR(306) binary comment '宣传材料名称',
	`FILEPATH` VARCHAR(615) binary comment '宣传材料地址',
	`CREATEDATE` DATETIME comment '创建日期'
)
comment='宣传材料';

create table if not exists `otc`.`GJ_G2010_PROD_SET_FEATURE_TEMP` (
	`PROD_FEATURE_LABEL` VARCHAR(120) binary,
	`CREATE_TIME` VARCHAR(60) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`FIRST_DETAIL_DISPLAY_CH` VARCHAR(120) binary,
	`SECOND_DETAIL_DISPLAY_CH` VARCHAR(120) binary,
	`FIRST_DETAIL_DISPLAY` VARCHAR(60) binary,
	`SECOND_DETAIL_DISPLAY` VARCHAR(60) binary,
	`TYPE` VARCHAR(3) binary,
	`INCOME_DESCRIBE` VARCHAR(600) binary
);

create table if not exists `otc`.`L_ORGANIZATION_SON_REL` (
	`ORG_ID` NUMERIC(19, 0) not null comment '营业部id',
	`ORG_SON` NUMERIC(19, 0) not null comment '子营业部id',
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`REC_UPD_TIME` DATETIME(6) comment '记录更新时间',
	constraint `BIN$JRvB0l4K0lrgYAB/AQBj0w==$0` primary key (`ORG_ID`, `ORG_SON`)
)
comment='营业部子营业对应关系';

create table if not exists `otc`.`GJ_G9010_WEEKLY_REPORT_DETAIL` (
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`ID` NUMERIC(19, 0) not null,
	`TASK_NAME` VARCHAR(1200) binary,
	`TASK_DUTY_PERSON` VARCHAR(24) binary,
	`TASK_IS_PERIOD` VARCHAR(3) binary,
	`TASK_QUANTITY` VARCHAR(12) binary,
	`DELIVERABLE` VARCHAR(120) binary,
	`SCHEDULE_STATUS` VARCHAR(240) binary,
	`FINISH_RATIO` VARCHAR(12) binary,
	`REMARK` VARCHAR(2400) binary,
	`REPORT_TYPE` VARCHAR(3) binary,
	`WEEKLY_LIST_ID` NUMERIC(19, 0),
	constraint `BIN$JRvB0led0lrgYAB/AQBj0w==$0` primary key (`ID`)
);

create table if not exists `otc`.`GJ_G2010_YHLC_SERIAL_DATA` (
	`APPLY_NO` VARCHAR(60) binary comment '申请编号',
	`APPLY_DATE` VARCHAR(24) binary comment '申请日期',
	`OP_REMARK` VARCHAR(306) binary comment '操作备注',
	`BUSIN_ACCOUNT` VARCHAR(60) binary comment '资金账户',
	`PROD_CODE` VARCHAR(12) binary comment '产品代码',
	`ENTRUST_BALANCE` VARCHAR(12) binary comment '申请金额',
	`ORDER_STATUS` VARCHAR(2) binary comment '操作状态("1"下单 "2"撤单)',
	`CUST_NUM` VARCHAR(60) binary comment '客户编号',
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通账户',
	`ORGID` VARCHAR(12) binary comment '营业部代码',
	`REC_GEN_TIME` DATETIME(6) comment '购买日期',
	`TRADE_TYPE` VARCHAR(12) binary comment '交易类别',
	`PROD_ID` VARCHAR(12) binary comment '多金产品编号',
	`GT_PRODUCTID` VARCHAR(12) binary comment '产品中心产品编号',
	`PROD_NAME` VARCHAR(60) binary comment '产品名称',
	`CID_SOURCE` VARCHAR(22) binary comment '订单来源(NEWMALL:理财频道)'
)
comment='银行理财多金流水数据';

create table if not exists `otc`.`GJ_G2010_IDX_MAKT_QUOT` (
	`PROD_CD` VARCHAR(24) binary,
	`CN_NAME` VARCHAR(240) binary
);

create table if not exists `otc`.`GJ_G2010_ITEM_RULE_INFO_SH` (
	`ID` NUMERIC(20, 0) not null,
	`ITEM_CODE` VARCHAR(10) binary,
	`RULE_CODE` VARCHAR(10) binary,
	`DESC_START` NUMERIC(8, 0),
	`BOLT_NUM` NUMERIC(8, 0),
	`OPER_ID` VARCHAR(60) binary,
	`CREATE_PERSONNEL` VARCHAR(24) binary,
	`CREATE_TIME` DATETIME,
	`UPD_TIME` DATETIME,
	`UPD_PERSONNEL` VARCHAR(24) binary,
	`AUDIT_STATUS` VARCHAR(3) binary,
	`USER_RULE_ID` VARCHAR(600) binary,
	`USER_RULE_ID_SPARE` VARCHAR(600) binary,
	`RULE_UUID` VARCHAR(60) binary,
	`BUTTON_IS_DISPLAY` VARCHAR(3) binary,
	`BUTTON_WORD_SHOW` VARCHAR(24) binary,
	`PC_BUTTON_LINK` VARCHAR(1200) binary,
	`BUTTON_LINK` VARCHAR(1200) binary,
	`BUTTON_LINK_TYPE` VARCHAR(12) binary,
	`PROD_DESCRIBE` VARCHAR(120) binary,
	`AUTO_REPALCE_DESCRIBE` VARCHAR(3) binary,
	`AUTO_REPLACE_DESCRIBE` VARCHAR(3) binary,
	`AUDIT_STATUS_SH` VARCHAR(3) binary,
	`IS_FIVE_PART` VARCHAR(3) binary,
	`URL` VARCHAR(1200) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`IS_SUPPORT_RED_DOT` VARCHAR(3) binary
);

create table if not exists `otc`.`GJ_SZ_V_QUESTIONNAIRE` (
	`VERSION_ID` VARCHAR(77) binary not null comment ' 问卷版本号 ',
	`ID` VARCHAR(77) binary not null comment ' 问题ID ',
	`QUESTION_NAME` VARCHAR(306) binary comment ' 问题标题 ',
	`QUESTION_DESC` VARCHAR(306) binary comment ' 问题描述 ',
	`QT_SORT` VARCHAR(27) binary comment ' 问题序号 ',
	`CHOOSE_NAME` VARCHAR(1200) binary comment ' 选项内容 ',
	`NEXT_QUESTION` VARCHAR(306) binary comment ' 选项对应下个问题ID ',
	`OPTION_RESULT` VARCHAR(306) binary comment ' 选项对应的策略ID ',
	`OPTION_TYPE` VARCHAR(77) binary comment ' （无用） ',
	`CE_SORT` VARCHAR(27) binary comment ' 选项序号 ',
	`RESULT_ID` VARCHAR(77) binary not null comment ' （无用） ',
	`RESULT_TITLE` VARCHAR(612) binary comment '  选项标题 ',
	`TAG1` VARCHAR(612) binary comment ' 风险描述 ',
	`TAG2` VARCHAR(612) binary comment ' 投资期限描述 ',
	`TAG3` VARCHAR(612) binary comment ' 投资目标描述 ',
	`OPTION_RESULT_DESC` VARCHAR(306) binary comment ' （无用） ',
	`RISK_CODE` VARCHAR(3) binary comment ' 产品风险等级 ',
	`PERSON_RISK_CODE` VARCHAR(3) binary comment ' 匹配的客户风险等级 ',
	`QUESTIONNARIE_TYPE` VARCHAR(306) binary comment ' 问卷类型，S-建议型，M-管理型 ',
	`EXTERNAL_CODE` VARCHAR(24) binary comment ' 问卷外部代码 ',
	`SOURCE_CODE` VARCHAR(24) binary comment ' 机构代码 ',
	`CUS_CODE` VARCHAR(120) binary comment '长客户代码'
)
comment='商智策略问卷表';

create table if not exists `otc`.`GJ_SZ_V_PRO_ROBOTS` (
	`ROBOT_ID` VARCHAR(77) binary not null comment '策略ID',
	`ROBOT_NAME` VARCHAR(306) binary comment '策略名称',
	`RISK_CODE` VARCHAR(12) binary comment '风险等级',
	`INVESTMENT_VARIETY` VARCHAR(12) binary comment ' 投资种类 ',
	`INVESTMENT_PERIOD` VARCHAR(2) binary comment ' 投资周期 ',
	`REMARK` VARCHAR(2400) binary comment ' 风险说明 ',
	`MANAGE_RATE_FEE` NUMERIC(10, 6) comment '管理费率',
	`DISCOUNT` NUMERIC(65, 30) comment '管理费折扣率',
	`PARAM_BENCHMARK_NAME` VARCHAR(306) binary comment ' 业绩比较基准 ',
	`RISK_REMARK` VARCHAR(2400) binary comment ' 风险说明(废弃) ',
	`PUBLIC_STATUS` VARCHAR(3) binary comment '发布状态',
	`BENCHMARK` VARCHAR(4800) binary comment ' 业绩比较基准 ',
	`EQ` NUMERIC(65, 30) comment '权益类占比',
	`MM` NUMERIC(65, 30) comment '现金类占比',
	`DCM` NUMERIC(65, 30) comment '固收类占比',
	`OTH` NUMERIC(65, 30) comment '创新类占比',
	`PCTBM` NUMERIC(65, 30) comment '  比较基准成立以来涨幅  ',
	`PCTBM1M` NUMERIC(65, 30) comment '  比较基准近1月涨幅  ',
	`PCTBM3M` NUMERIC(65, 30) comment '  比较基准近3月涨幅 ',
	`PCTBM6M` NUMERIC(65, 30) comment '  比较基准近6月涨幅 ',
	`PCTBM1Y` NUMERIC(65, 30) comment '  比较基准近1年涨幅 ',
	`PCT` NUMERIC(65, 30) comment '成立以来收益率',
	`PCT1M` NUMERIC(65, 30) comment ' 近1月收益率 ',
	`PCT3M` NUMERIC(65, 30) comment '近3月收益率',
	`PCT6M` NUMERIC(65, 30) comment '近6月收益率',
	`PCT1Y` NUMERIC(65, 30) comment '近1年收益率',
	`DDR` NUMERIC(65, 30) comment ' 成立以来最大回撤 ',
	`DDR1M` NUMERIC(65, 30) comment '  近一月最大回撤  ',
	`DDR3M` NUMERIC(65, 30) comment ' 近三月最大回撤 ',
	`DDR6M` NUMERIC(65, 30) comment ' 近六月最大回撤 ',
	`DDR1Y` NUMERIC(65, 30) comment ' 近一年最大回撤 ',
	`SHP` NUMERIC(65, 30) comment ' 成立以来夏普率 ',
	`SHP1M` NUMERIC(65, 30) comment ' 近1月夏普率 ',
	`SHP3M` NUMERIC(65, 30) comment ' 近3月夏普率 ',
	`SHP6M` NUMERIC(65, 30) comment ' 近6月夏普率 ',
	`SHP1Y` NUMERIC(65, 30) comment ' 近1年夏普率 ',
	`BMPCT` NUMERIC(24, 6) comment '  比较基准成立以来涨幅  ',
	`CREATE_DT` DATETIME(6) not null comment '创建日期',
	`CREATE_BY` VARCHAR(77) binary not null,
	`MODIFY_DT` DATETIME(6) comment '修改日期',
	`MODIFY_BY` VARCHAR(77) binary comment '修改人',
	`PRODUCT_ALLOCATION` VARCHAR(306) binary comment ' （无用） ',
	`STRATEGY_LOSS_LEVEL` VARCHAR(306) binary comment ' 最大可承受损失 ',
	`PURCHASE_AMOUNT_C` NUMERIC(10, 2) comment ' 最低首次金额 ',
	`ADDITIONAL_AMOUNT_C` NUMERIC(10, 2) comment ' 最少追加金额 ',
	`DATA_DT` VARCHAR(12) binary comment ' 数据基准日期 ',
	`PF_CUSTOMIZED_TYPE` VARCHAR(12) binary comment ' （无用） ',
	`SELL_STAT` VARCHAR(3) binary comment '销售状态',
	`SHELVES_DATE` DATETIME(6) comment '上架日期',
	`DAY` NUMERIC(65, 30) comment '成立天数',
	`ADSR` NUMERIC(65, 30) comment '下行波动率',
	`PCTCY` NUMERIC(65, 30) comment '今年以来收益率',
	`OPERATING_MODE` VARCHAR(3) binary comment '操作类型 1：建议型 2：管理型',
	`QDII_FLAG` VARCHAR(3) binary comment '是否包含QDII  0:否 1：是',
	`PRIVATE_PRODUCT_FLAG` VARCHAR(3) binary comment '是否含有私募 0：否 1：是',
	`SUGGESTIVE_CHARGE_TYPE` VARCHAR(3) binary comment '建议型收费方式 1：按费率  2：一次性收费',
	`SUGGESTIVE_RATE` NUMERIC(10, 6) comment '建议型费率',
	`SINGLE_CHARGE_AMOUNT` NUMERIC(10, 6) comment '一次性收费金额',
	`CHARGE_FREQUENCY` VARCHAR(120) binary comment '收费频率 M:月 Q:季 Y:年',
	`PURCHASE_AMOUNT_B` NUMERIC(65, 30),
	`ADDITIONAL_AMOUNT_B` NUMERIC(65, 30),
	`PURCHASE_MAX_AMOUNT_C` NUMERIC(65, 30),
	`PURCHASE_MAX_AMOUNT_B` NUMERIC(65, 30),
	`ADDITIONAL_MAX_AMOUNT_C` NUMERIC(65, 30),
	`ADDITIONAL_MAX_AMOUNT_B` NUMERIC(65, 30),
	`SERVICE_CODE` VARCHAR(120) binary comment '投顾服务产品编号',
	`CERTIFICATE_CODE` VARCHAR(120) binary comment '投顾执业证书编号',
	`CREATE_BY_NAME` VARCHAR(120) binary comment '投资经理姓名'
)
comment='商智策略基础表';

create table if not exists `otc`.`GJ_G2050_REDEEM` (
	`ID` NUMERIC(20, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`SECUM_ACCOUNT` VARCHAR(60) binary,
	`CUST_NAME` VARCHAR(60) binary,
	`CUST_ADDRESS` VARCHAR(240) binary,
	`PRO_NAME` VARCHAR(60) binary,
	`PROD_CODE` VARCHAR(60) binary,
	`EXCEEDFLAG` VARCHAR(60) binary,
	`REDEEM_AMOUNT` NUMERIC(20, 0),
	`REDEEM_INFO` VARCHAR(240) binary,
	`ALLOT_NO` VARCHAR(60) binary,
	`INIT_DATE` VARCHAR(60) binary,
	`DEAL_INFO` VARCHAR(60) binary,
	`ENTRUST_DATE` DATETIME(6),
	`DEAL_FLAG` VARCHAR(60) binary,
	`SERIAL_NO` VARCHAR(60) binary,
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`PROD_TYPE_CHILD` VARCHAR(12) binary,
	constraint `BIN$JRvB0lcH0lrgYAB/AQBj0w==$0` primary key (`ID`)
)
comment='私募基金赎回';

create table if not exists `otc`.`GJ_G2010_PROD_SET_INFO_SH` (
	`SET_CODE` VARCHAR(12) binary not null comment '产品组合代码',
	`FORCE_SHOW_KEY` VARCHAR(3) binary comment '强制展示名称和标签',
	`NO_OPEN_CONTXT` VARCHAR(60) binary comment '非公开产品展示内容',
	`SET_NAME` VARCHAR(36) binary comment '产品组合名称',
	`SHT_NAME` VARCHAR(36) binary comment '产品组合简称',
	`COMM` NUMERIC(19, 6) comment '成立来收益率',
	`COMM_1M` NUMERIC(19, 6) comment '近一个月收益率',
	`COMM_3M` NUMERIC(19, 6) comment '近一个季度收益率',
	`COMM_6M` NUMERIC(19, 6) comment '近半年收益率',
	`COMM_1Y` NUMERIC(19, 6) comment '近一年收益率',
	`COMM_DRAWDOWN` NUMERIC(19, 6) comment '历史最大回撤收益率',
	`PROD_LABEL` VARCHAR(24) binary comment '组合右上角标签',
	`PROD_RIGHT_LABEL_CTXT` VARCHAR(60) binary comment '组合右上角标签配置',
	`PROD_FEATURE_LABEL` VARCHAR(60) binary comment '组合特点标签',
	`PROD_FEATURE_DESCRIBE` VARCHAR(240) binary comment '组合特点描述',
	`SHOW_BEGIN` DATETIME comment '展示开始时间',
	`SHOW_END` DATETIME comment '展示结束时间',
	`WEEKS` VARCHAR(240) binary comment '周',
	`DAILY_BEGIN_TIME` VARCHAR(24) binary comment '每日展示开始时间',
	`DAILY_END_TIME` VARCHAR(24) binary comment '每日展示结束时间',
	`APP_DETAIL_URL` VARCHAR(600) binary comment 'APP详情URL',
	`MALL_DETAIL_URL` VARCHAR(600) binary comment '君弘网URL',
	`PC_DETAIL_URL` VARCHAR(600) binary comment 'PC详情URL',
	`FIRST_DETAIL_DISPLAY_CH` VARCHAR(240) binary comment '详情高优先字段显示',
	`SECOND_DETAIL_DISPLAY_CH` VARCHAR(240) binary comment '详情低优先字段显示',
	`LIMIT_TYPE` VARCHAR(12) binary comment '剩余额度展示类型',
	`SEARCH_IS_ALLOWED` VARCHAR(3) binary comment '是否允许被搜索',
	`NO_SELL_DISPLAY` VARCHAR(3) binary comment '不可售产品是否展示',
	`NOLOGIN_IS_DISPLAY` VARCHAR(3) binary comment '未登录是否可见',
	`TICKET_NUM` VARCHAR(3) binary comment '是否根据活动代码定向展示',
	`STL_RISK_TYPE` VARCHAR(12) binary,
	`ATTENTION_PERSON` NUMERIC(9, 0),
	`FIXED_INCREMENTAL_VALUE` NUMERIC(9, 0),
	`PERFORMANCE_BENCHMARKS` VARCHAR(120) binary,
	`SET_STRATEGY_TYPE` VARCHAR(60) binary,
	`SET_STRATEGY_INFO` VARCHAR(1200) binary,
	`STRATEGY_MODEL_NAME` VARCHAR(60) binary,
	`STRATEGY_MODEL_INFO` VARCHAR(1200) binary,
	`INCOME_INFO` VARCHAR(3600) binary,
	`TEAM_NAME` VARCHAR(60) binary,
	`TEAM_INFO` VARCHAR(600) binary,
	`CONSULTANT_NAME` VARCHAR(24) binary,
	`CONSULTANT_COMPANY` VARCHAR(36) binary,
	`CONSULTANT_JOB_ID` VARCHAR(24) binary,
	`CONSULTANT_IMAGE_ID` VARCHAR(120) binary,
	`CONSULTANT_IMAGE_NAME` VARCHAR(120) binary,
	`CONSULTANT_IMAGE_DESCRIBE` VARCHAR(60) binary,
	`CONSULTANT_IMAGE_URL` VARCHAR(600) binary,
	`DETAIL_FIELD_NAME` VARCHAR(60) binary,
	`SUPER_FIELD` VARCHAR(60) binary,
	`FIELD_SUBCLASS` VARCHAR(60) binary,
	`FIELD_INFO` VARCHAR(2400) binary,
	`AUDIT_STATUS` VARCHAR(2) binary,
	`BUY_STATUS` VARCHAR(3) binary,
	`COMM_PRIORITY` NUMERIC(9, 0),
	`COMM_1M_PRIORITY` NUMERIC(9, 0),
	`COMM_3M_PRIORITY` NUMERIC(9, 0),
	`COMM_6M_PRIORITY` NUMERIC(9, 0),
	`COMM_1Y_PRIORITY` NUMERIC(9, 0),
	`COMM_DRAWDOWN_PRIORITY` NUMERIC(9, 0),
	`SET_CREATE_TIME` DATETIME,
	`PROD_TYPE` VARCHAR(3) binary,
	`CREATE_PERSONNEL` VARCHAR(60) binary,
	`SET_UPDATE_TIME` DATETIME comment '修改时间',
	`UPDATE_PERSONNEL` VARCHAR(60) binary,
	`YD_URL_NAME` VARCHAR(120) binary comment '移动端跳转地址名称',
	`JH_URL_NAME` VARCHAR(120) binary comment '君弘网跳转地址名称',
	`PC_URL_NAME` VARCHAR(120) binary comment 'PC端跳转地址名称',
	`RATE_POSTFIX` VARCHAR(12) binary comment '收益率后缀',
	`FIRST_DETAIL_DISPLAY` VARCHAR(60) binary comment '详情高优先字段',
	`SECOND_DETAIL_DISPLAY` VARCHAR(60) binary comment '详情低优先字段',
	`BEGIN_DATE` VARCHAR(60) binary comment '开始日期',
	`BEGIN_TIME` VARCHAR(60) binary comment '开始时间',
	`END_DATE` VARCHAR(60) binary comment '结束日期',
	`END_TIME` VARCHAR(60) binary comment '结束时间',
	`OPER_ID` VARCHAR(306) binary comment '（不知含义）',
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
)
comment='产品信息设置';

create table if not exists `otc`.`FUND_INVEST_TRANSFER_SERIAL` (
	`CIF_ACCOUNT` VARCHAR(60) binary comment '一户通号',
	`BUSIN_ACCOUNT` VARCHAR(60) binary not null comment '客户资金账号',
	`BANK_NO` VARCHAR(5) binary comment '银行编号',
	`BANK_NAME` VARCHAR(60) binary comment '银行名称',
	`TRANSFER_DIRECTION` CHAR(1) binary comment '1-转入，2-转出，3-赎回',
	`MONEY_TYPE` CHAR(1) binary not null comment '币种',
	`OCCUR_BALANCE` VARCHAR(23) binary not null comment '转账金额',
	`CLEAR_BALANCE` VARCHAR(23) binary comment '账户余额',
	`EN_FUNCTION_TYPE` VARCHAR(60) binary not null comment '策略编号',
	`ENTRUST_NO` VARCHAR(60) binary not null comment '委托编号',
	`ENTRUST_DATE` VARCHAR(12) binary comment '委托日期',
	`ENTRUST_TIME` VARCHAR(12) binary comment '委托时间',
	`BKTRANS_STATUS` CHAR(1) binary comment '0-未报,1-已报,2-成功,3-失败,4-超时,5-待冲正,6-已冲正,7-调整为成功,8-调整为失败',
	`BANK_ERROR_NO` VARCHAR(12) binary comment '银行错误编号',
	`BANK_ERROR_INFO` VARCHAR(600) binary comment '银行错误信息',
	`ERROR_INFO` VARCHAR(600) binary comment '集中交易错误信息',
	`ERROR_NO` VARCHAR(12) binary comment '集中交易错误编号',
	`CHANNEL` VARCHAR(306) binary comment '发起渠道',
	`EXTRA` VARCHAR(306) binary comment '附加信息',
	`REDEEM_PERCENT` VARCHAR(9) binary comment '赎回比例',
	`MAIN_BUSIN_ACCOUNT` VARCHAR(60) binary comment '主资金账号',
	`SOURCE` VARCHAR(12) binary comment '渠道 JRSC:金融商城  XST:销售通'
)
comment='基金投顾流水表';

create table if not exists `otc`.`GJ_G2010_PRODT_RATET_INFO` (
	`PROD_TYPE` VARCHAR(3) binary comment '产品类型',
	`RATE_TYPE` VARCHAR(120) binary comment '收益率类型（中文）',
	`PRIORITY` NUMERIC(19, 0) comment '收益率展示优先级',
	`COL_NAME` VARCHAR(60) binary comment '收益率字段名',
	`TYPE` VARCHAR(3) binary comment '类型(1、收益率  2、销量  3、购买人数)',
	`TYPE2` VARCHAR(3) binary comment '类型2(1.常规类型，2.限定特殊类型，3.两者共用)'
)
comment='产品类型对应收益率类型表';

create table if not exists `otc`.`GJ_CUST_INFO` (
	`CUST_NUM` VARCHAR(24) binary not null comment '客户编号',
	`NAME` VARCHAR(120) binary comment '姓名',
	`AGE` NUMERIC(10, 0) comment '年龄',
	`SEX` VARCHAR(2) binary comment '性别',
	`ORG_NUM` NUMERIC(19, 0) comment '所属营业部',
	`DEP_NUM` NUMERIC(19, 0) comment '所属分公司',
	`CUST_MANAGER` VARCHAR(180) binary comment '客户经理',
	`MARKET_VALUE` NUMERIC(19, 0) comment '市值',
	`MOBILE` VARCHAR(120) binary comment '手机号',
	`CUST_TYPE` VARCHAR(2) binary not null comment '客户类型',
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`REC_UPD_TIME` DATETIME(6) comment '记录更新时间',
	`CUST_MANAGER_MOBILE` VARCHAR(420) binary comment '客户经理手机号码',
	`FUND_ACCOUNT` VARCHAR(120) binary comment '资金账号',
	`CARD_NUM` VARCHAR(60) binary comment '身份证号',
	`MEMBER_FLG` VARCHAR(2) binary comment '君弘会员',
	`ASSET` NUMERIC(19, 4) comment '总资产',
	`MARRIAGE_FLG` VARCHAR(2) binary comment '婚姻状况',
	`MANAGER_FLG` VARCHAR(2) binary comment '是否董监高',
	`RISK_REMARK` VARCHAR(600) binary comment '风险自述',
	`EMAIL` VARCHAR(60) binary comment '邮箱',
	`RISK_GRADE` VARCHAR(60) binary,
	`MOBILE_UPDATE` VARCHAR(48) binary comment '号码更新',
	`ADDR_UPDATE` VARCHAR(48) binary,
	`OPEN_TIME` NUMERIC(20, 0),
	`ADDRESS` VARCHAR(600) binary,
	`MAX_HALFASSET_DATE` VARCHAR(10) binary,
	`MAX_HALFYEAR_ASSET` NUMERIC(65, 30),
	constraint `BIN$JRvB0lTu0lrgYAB/AQBj0w==$0` primary key (`CUST_NUM`)
)
comment='客户基本信息';

create table if not exists `otc`.`GJ_G2010_T2SDK_LOG` (
	`REC_GEN_TIME` DATETIME(6),
	`REC_UPD_TIME` DATETIME(6),
	`LSH` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(60) binary,
	`FUND_ACCOUNT` VARCHAR(60) binary,
	`FUNCTION_ID` VARCHAR(24) binary,
	`BIZ_DATE` DATETIME,
	`KBN` CHAR(1) binary,
	`RESULT` LONGTEXT,
	`CIF_ACCOUNT` VARCHAR(60) binary,
	`PARAMETER` LONGTEXT,
	`SERIAL_NO` VARCHAR(60) binary,
	`CALL_TIME` NUMERIC(8, 0),
	constraint `BIN$JRvB0laF0lrgYAB/AQBj0w==$0` primary key (`LSH`)
);

create table if not exists `otc`.`GJ_FYCJ_CONDITION` (
	`CUST_NUM` VARCHAR(24) binary,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(24) binary,
	`CODE` VARCHAR(60) binary not null,
	`AWARD` VARCHAR(60) binary,
	`LOTTERY_FLAG` CHAR(1) binary,
	`FUND_ACCOUNT` VARCHAR(24) binary,
	`AWARD_FLAG` CHAR(1) binary,
	`PHONE_NUM` VARCHAR(24) binary,
	`SCRATCH_TIME` DATETIME,
	`CASH_TIME` DATETIME,
	`PHONE_NUM_GIVEN` VARCHAR(60) binary,
	`CERTIFICATE_TYPE` VARCHAR(24) binary,
	constraint `BIN$JRvB0lUS0lrgYAB/AQBj0w==$0` primary key (`CODE`)
)
comment='富易抽奖用户表';

create table if not exists `otc`.`JG_OUT_CUST_INFO` (
	`CUST_ID` VARCHAR(48) binary,
	`CUST_MANAGER` VARCHAR(180) binary,
	`MAN_MOBILE` VARCHAR(420) binary
);

create table if not exists `otc`.`L_ORGANIZATION` (
	`ORG_ID` NUMERIC(19, 0) not null comment '部门ID',
	`ORG_NAME` VARCHAR(60) binary comment '部门名称',
	`ORG_DESC` VARCHAR(600) binary comment '部门描述',
	`SUPER_ID` NUMERIC(19, 0) comment '上级部门ID',
	`ORG_TYPE` VARCHAR(24) binary comment '部门类型',
	`DELETE_FLAG` NUMERIC(10, 0) comment '逻辑删除标示，1为删除，0为未删除',
	`ORG_NUM` VARCHAR(120) binary comment '编号',
	`REC_VERSION` NUMERIC(19, 0) comment '乐观锁',
	`REC_GEN_TIME` DATETIME(6) comment '记录生成时间',
	`REC_UPD_TIME` DATETIME(6) comment '记录更新时间',
	constraint `BIN$JRvB0l4B0lrgYAB/AQBj0w==$0` primary key (`ORG_ID`)
)
comment='部门表';

create table if not exists `otc`.`GJ_WORK_ATTENDENCE_MIDDLE` (
	`NAME` VARCHAR(12) binary not null,
	`WORK_UID` VARCHAR(36) binary not null,
	`CARD_NO` VARCHAR(12) binary not null,
	`WORK_DAY` VARCHAR(120) binary not null,
	`ON_DUTY_TIME` VARCHAR(120) binary,
	`OFF_DUTY_TIME` VARCHAR(120) binary,
	`WORK_HOURS` VARCHAR(6) binary,
	`WORK_STATE` VARCHAR(10) binary,
	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP
);

create table if not exists `otc`.`GJ_LOTTERY_LS` (
	`CUST_NUM` VARCHAR(24) binary comment '客户代码',
	`USER_CODE` VARCHAR(22) binary comment '用户代码',
	`CIF_ACCOUNT` VARCHAR(24) binary comment '一户通账号',
	`PROJECT_ID` VARCHAR(24) binary comment '项目ID',
	`PRIZE_NAME` VARCHAR(60) binary comment '奖品',
	`AWARD_FLAG` NUMERIC(1, 0) comment '奖品标识',
	`LOTTERY_AMOUNT` NUMERIC(8, 0) comment '中奖数量',
	`LOTTERY_TIME` DATETIME comment '抽奖日期',
	`PHONE_NUM` VARCHAR(24) binary comment '手机号码'
)
comment='抽奖流水表';

create table if not exists `otc`.`OLD_NEW_TABLE_NAME` (
	`OLD_TABLE_NAME` VARCHAR(306) binary,
	`NEW_TABLE_NAME` VARCHAR(306) binary,
	`COMMENT_ZH` VARCHAR(306) binary,
	`IS_DONE` VARCHAR(306) binary,
	`CREATE_DATE` DATETIME
);

create table if not exists `otc`.`GJ_OTC_MALLTRADE_FUNDCAN_LS` (
	`ID` NUMERIC(19, 0) not null,
	`CUST_NUM` VARCHAR(24) binary not null,
	`USER_CODE` VARCHAR(22) binary,
	`CIF_ACCOUNT` VARCHAR(24) binary,
	`FUND_ACCOUNT` VARCHAR(24) binary,
	`ENTRUST_NO_BEFORE` VARCHAR(24) binary,
	`ALLOT_TIME` VARCHAR(10) binary,
	`TRADE_TIME` VARCHAR(24) binary,
	`FUND_COMPANY` VARCHAR(60) binary,
	`FUND_CODE` VARCHAR(60) binary,
	`FUND_NAME` VARCHAR(60) binary,
	`ENTRUST_NO_AFTER` VARCHAR(24) binary,
	`BALANCE` VARCHAR(24) binary,
	`AMOUNT` VARCHAR(24) binary,
	`SERIAL_NO` VARCHAR(18) binary
)
comment='场内基金撤单流水';