CREATE TABLE `GJ_G9010_PRO_TEST_INFO` (
  	`BUG_NUM` NUMERIC(8, 0) not null,
  	`PROJECT_NUM` VARCHAR(6) binary,
  	`BUG_TITLE` VARCHAR(240) binary,
  	`BUG_TIME` DATETIME,
  	`TEST_PERSONNEL` VARCHAR(24) binary,
  	`REPAIR_PERSONNEL` VARCHAR(24) binary,
  	`REPAIR_STATUS` VARCHAR(2) binary,
  	`BUG_DESCRIBE` VARCHAR(2400) binary,
  	`REPAIR_WAY` VARCHAR(2400) binary,
  	`IDENTIFY_ID` VARCHAR(120) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G9010_PRO_CHANGE_LST` (
  	`REC_GEN_TIME` DATETIME(6),
  	`REC_UPD_TIME` DATETIME(6),
  	`DEMAND_NUM` NUMERIC(19, 0) not null,
  	`PROJECT_NUM` VARCHAR(36) binary,
  	`DEMAND_TITLE` VARCHAR(120) binary,
  	`DEMAND_TYPE` VARCHAR(2) binary,
  	`DEMAND_DESCRIBE1` VARCHAR(4800) binary,
  	`DEMAND_REMARK` VARCHAR(2400) binary,
  	`DEMAND_STATUS` VARCHAR(2) binary,
  	`EXP_BEGIN_DATE` DATETIME,
  	`EXP_END_DATE` DATETIME,
  	`ACT_BEGIN_DATE` DATETIME,
  	`ACT_END_DATE` DATETIME,
  	`DEMAND_LEADER` VARCHAR(36) binary,
  	`DEMAND_DESCRIBE` LONGTEXT,
  	`IDENTIFY_ID` VARCHAR(120) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	constraint `BIN$JRvB0ld60lrgYAB/AQBj0w==$0` primary key (`DEMAND_NUM`),
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G9010_PRO_QUESTION_LST` (
  	`REC_GEN_TIME` DATETIME(6),
  	`REC_UPD_TIME` DATETIME(6),
  	`TROUBLE_NUM` NUMERIC(19, 0) not null,
  	`PROJECT_NUM` VARCHAR(120) binary,
  	`TROUBLE_DATE` DATETIME,
  	`TROUBLE_TITLE` VARCHAR(60) binary,
  	`TROUBLE_DESCRIBE` VARCHAR(2400) binary,
  	`TROUBLE_RESOLVENT` VARCHAR(4800) binary,
  	`IDENTIFY_ID` VARCHAR(120) binary,
  	`PROJECT_NUM_CH` VARCHAR(600) binary,
  	`AUTHOR` VARCHAR(24) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	constraint `BIN$JRvB0leG0lrgYAB/AQBj0w==$0` primary key (`TROUBLE_NUM`),
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G3020_PROD_TARGET_INFO` (
  	`ID` VARCHAR(23) binary comment 'ID',
  	`TARGET_ID` VARCHAR(24) binary comment '标的ID',
  	`TARGET_CONTEXT` VARCHAR(60) binary comment '标的内容',
  	`CREATE_DATE` DATETIME,
  	`UPDATE_PERSONNEL` VARCHAR(24) binary,
  	`UPDATE_DATE` DATETIME,
  	`TYPE` VARCHAR(3) binary comment '类型',
  	`SUPER_ID` VARCHAR(24) binary comment '上一级ID',
  	`CREATE_PERSONNEL` VARCHAR(24) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) comment='标的类型配置';

CREATE TABLE `GJ_G2019_MARKETING_RULES` (
  	`ID` VARCHAR(10) binary,
  	`MARKETING_RULE_ID` VARCHAR(20) binary,
  	`MARKETING_RULE_NAME` VARCHAR(20) binary,
  	`MARKETING_RULE_REMARK` VARCHAR(20) binary,
  	`CREATE_TIME` VARCHAR(10) binary,
  	`CREATE_PERSONNEL` VARCHAR(20) binary,
  	`EFFECT_SCENE_TYPE` VARCHAR(3) binary,
  	`UPD_TIME` VARCHAR(20) binary,
  	`UPD_PERSONNEL` VARCHAR(20) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2019_RULES_ITEM` (
  	`ID` VARCHAR(20) binary,
  	`ITEM_CODE` VARCHAR(20) binary,
  	`MARKETING_RULE_ID` VARCHAR(20) binary comment '营销规则栏目代码',
  	`ITEM_NAME` VARCHAR(154) binary,
  	`MARKETING_RULE_NAME` VARCHAR(154) binary,
  	`SHELF_TYPE` VARCHAR(3) binary comment '货架类型',
  	`SHELF_BROWSE_WAY` VARCHAR(3) binary comment '货架阅读方式',
  	`PROD_WITH_ENHANCED` VARCHAR(3) binary comment '伴随式增强',
  	`ITEM_TYPE` VARCHAR(3) binary comment '栏目类型',
  	`ITEM_CODE_SUPER` VARCHAR(10) binary comment '上级栏目代码',
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2019_RULES_PROD` (
  	`ID` VARCHAR(20) binary,
  	`PROD_CODE` VARCHAR(77) binary comment '产品代码',
  	`PROD_NAME` VARCHAR(77) binary comment '产品名称',
  	`MARKETING_RULE_ID` VARCHAR(20) binary,
  	`MARKETING_RULE_NAME` VARCHAR(154) binary,
  	`PROD_TYPE` VARCHAR(3) binary comment '产品类型代码',
  	`PROD_TYPE_CHILD` VARCHAR(20) binary comment '产品子类代码',
  	`PROD_TYPE_CHILD_NAME` VARCHAR(154) binary comment '产品子类名称',
  	`PROD_TYPE_NAME` VARCHAR(154) binary comment '产品类型名称',
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2010_PROD_SET_ASSET_TEMP` (
  	`ASSET_ID` NUMERIC(65, 30),
  	`SET_CODE` VARCHAR(8) binary,
  	`ASSET_TYPE` VARCHAR(24) binary,
  	`ASSET_RATE` VARCHAR(60) binary,
  	`UPD_TIME` VARCHAR(60) binary,
  	`PRIORITY` NUMERIC(3, 0),
  	`UPD_PERSONNEL` VARCHAR(24) binary,
  	`CREATE_TIME` VARCHAR(60) binary,
  	`CREATE_PERSONNEL` VARCHAR(24) binary,
  	`TRANSFERWH_ID` NUMERIC(65, 30),
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2010_PROD_SET_WHINFO_TEMP` (
  	`WHINFO_ID` NUMERIC(65, 30),
  	`PROD_CODE` VARCHAR(12) binary,
  	`PROD_NAME` VARCHAR(60) binary,
  	`ASSET_ID` NUMERIC(65, 30),
  	`VIEWPOINT` VARCHAR(2400) binary,
  	`PROD_RATE` VARCHAR(6) binary,
  	`PRIORITY` NUMERIC(3, 0),
  	`UPD_TIME` VARCHAR(60) binary,
  	`UPD_PERSONNEL` VARCHAR(24) binary,
  	`SET_CODE` VARCHAR(12) binary,
  	`CREATE_PERSONNEL` VARCHAR(24) binary,
  	`CREATE_TIME` VARCHAR(60) binary,
  	`TRANSFERWH_ID` NUMERIC(65, 30),
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2010_HOME_PAGE_SVCINFO` (
  	`BIG_INFO_TYPE` VARCHAR(60) binary,
  	`BIG_PRIORITY` VARCHAR(10) binary,
  	`SMALL_INFO_TYPE` VARCHAR(60) binary,
  	`SMALL_PRIORITY` VARCHAR(10) binary,
  	`USER_RULE` VARCHAR(120) binary,
  	`IS_AUTO_GENERATE` VARCHAR(3) binary,
  	`IS_REGULAR_PUSH` VARCHAR(3) binary,
  	`BEGIN_DATE` VARCHAR(60) binary,
  	`BEGIN_TIME` VARCHAR(60) binary,
  	`END_DATE` VARCHAR(60) binary,
  	`END_TIME` VARCHAR(60) binary,
  	`INFO_CONTENT` VARCHAR(1229) binary,
  	`APP_URL` VARCHAR(360) binary,
  	`CREATE_TIME` VARCHAR(60) binary,
  	`CREATE_PERSONNEL` VARCHAR(60) binary,
  	`UPDATE_TIME` VARCHAR(60) binary,
  	`UPDATE_PERSONNEL` VARCHAR(60) binary,
  	`START_SHOW_TIME` DATETIME,
  	`END_SHOW_TIME` DATETIME,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2082_PROD_REL_TEMP` (
  	`ID` VARCHAR(24) binary,
  	`STRATEGY_CODE` VARCHAR(24) binary,
  	`PROD_CODE` VARCHAR(24) binary,
  	`PROD_DESCRIBE` VARCHAR(120) binary,
  	`PRIORITY` NUMERIC(2, 0),
  	`ROW_NUM` VARCHAR(24) binary,
  	`CREATE_PERSONNEL` VARCHAR(24) binary,
  	`CREATE_DATE` CHAR(10) binary,
  	`INVEST_TYPE` VARCHAR(24) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) comment='策略基金临时表';

CREATE TABLE `GJ_INDEX_FLUCTUATE_INFO` (
  	`INDEX_CHANCE` VARCHAR(3) binary comment '指数机会',
  	`INDEX_NUMBER` VARCHAR(20) binary comment '指数期数',
  	`ID` VARCHAR(24) binary not null comment '主键',
  	`UPLOAD_TIME` VARCHAR(29) binary comment '上线时间',
  	`INDEX_NAME` VARCHAR(306) binary comment '指数名称',
  	`INDEX_CODE` VARCHAR(144) binary comment '指数代码',
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP comment '创建时间',
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP comment '更新时间',
  	`AUDIT_STATUS` VARCHAR(15) binary comment '审核状态 1审核通过  2 待审核  3审核未通过 5删除待审核',
  	`CREATE_PERSONNEL` VARCHAR(44) binary comment '创建人',
  	`UPD_PERSONNEL` VARCHAR(44) binary comment '更新人',
  	`ORDER_ID` NUMERIC(16, 0) comment '期数+机会（用来排序）',
  	`INDEX_SUFFIX` VARCHAR(120) binary comment '指数代码后缀',
  	`COPYWRITING` VARCHAR(306) binary comment '运营文案',
  	`COPYWRITING_URL` VARCHAR(306) binary comment '运营文案链接',
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) comment='指数挺举指数波动';

CREATE TABLE `GJ_INDEX_FLUCTUATE_KV` (
  	`ID` VARCHAR(24) binary not null,
  	`KV_URL` VARCHAR(615) binary comment 'KVurl',
  	`IMG_URL` VARCHAR(615) binary,
  	`IMG_NAME` VARCHAR(306) binary,
  	`IMG_ID` VARCHAR(615) binary,
  	`INDEX_ID` NUMERIC(20, 0) comment '指数id',
  	`PRIORITY` VARCHAR(15) binary comment '优先级',
  	`CREATE_PERSONNEL` VARCHAR(30) binary,
  	`UPD_PERSONNEL` VARCHAR(30) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) comment='指数投教KV';

CREATE TABLE `FUND_MANAGE_LABEL_SH` (
  	`ID` VARCHAR(306) binary,
  	`PERSONCODE` VARCHAR(60) binary,
  	`LABEL` VARCHAR(60) binary,
  	`PRIORITY` NUMERIC(65, 30),
  	`UPDATE_DATE` DATETIME,
  	`UPDATE_PERSONNEL` VARCHAR(60) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2010_KNOWLEDGE_BASE` (
  	`ID` VARCHAR(10) binary,
  	`KNOWLEDGE_NAME` VARCHAR(60) binary,
  	`KNOWLEDGE_CONTENT` VARCHAR(600) binary,
  	`KNOWLEDGE_DESCRIBE` VARCHAR(240) binary,
  	`ABOUT_MODULE` VARCHAR(240) binary,
  	`UPDATE_TIME` DATETIME,
  	`UPDATE_PERSON` VARCHAR(24) binary,
  	`CREATE_TIME` DATETIME,
  	`CREATE_PERSON` VARCHAR(24) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `INTERFACE_GATE` (
  	`ENV` VARCHAR(12) binary not null comment '环境： local、200、sit、uat',
  	`STATUS` CHAR(1) binary not null comment '是否生效：0不生效，1生效',
  	`FUNCTION_ID` VARCHAR(24) binary not null comment '功能号',
  	`CLIENT_ID` VARCHAR(24) binary comment '客户代码',
  	`ID` VARCHAR(600) binary comment 'ID唯一标识',
  	`RESULT` LONGTEXT not null comment '响应结果集，必需为json数组',
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `GJ_G2010_MARKET_PERIOD_INFO` (
  	`ITEM_CODE` VARCHAR(10) binary,
  	`MARKET_ID` VARCHAR(10) binary,
  	`RATE_TYPE` CHAR(2) binary,
  	`PERIOD_REMARK` VARCHAR(120) binary,
  	`OBJECT_CODE` VARCHAR(120) binary,
  	`BENCHMARK_CODE` VARCHAR(120) binary,
  	`CREATE_PERSONNEL` VARCHAR(24) binary,
  	`CREATE_TIME` DATETIME,
  	`UPD_TIME` DATETIME,
  	`UPD_PERSONNEL` VARCHAR(24) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `LCODER_TABLES_RECORD_SQL` (
  	`ID` VARCHAR(306) binary not null,
  	`TABLE_NAME` VARCHAR(77) binary,
  	`OWNER` VARCHAR(20) binary,
  	`INDEX_ID` VARCHAR(306) binary,
  	`EXECUTE_SQL` VARCHAR(615) binary,
  	`LCODER_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`LCODER_UPDATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`OPERATOR_PERSON` VARCHAR(20) binary,
  	`OPERATOR_TYPE` VARCHAR(3) binary,
  	`EXCUTE_STATUS` VARCHAR(3) binary comment '审核表删除标志位: 删除标志设1, 删除审核执行删除: 标志1+表名',
  	`IS_DELETED` VARCHAR(3) binary default 0,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;

CREATE TABLE `LCODER_TABLES_RECORD_SQL_MYSQL` (
  	`ID` VARCHAR(306) binary not null,
  	`FROM_TABLE_NAME` VARCHAR(306) binary,
  	`TO_TABLE_NAME` VARCHAR(306) binary,
  	`INDEX_ID` VARCHAR(306) binary,
  	`EXECUTE_SQL` VARCHAR(4800) binary,
  	`SQL_CREATE_TIME` DATETIME default CURRENT_TIMESTAMP,
  	`JOB_EXCUTE_TIME` DATETIME default NULL,
  	`EXCUTE_STATUS` VARCHAR(3) binary comment '0:未执行,
  1:成功,
  2:失败',
  	`MSG` VARCHAR(4800) binary,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ;